using System.Runtime.CompilerServices;

#if GENIES_SDK && !GENIES_INTERNAL
// com.genies.sdk.avatareditor
[assembly: InternalsVisibleTo("Genies.Sdk.AvatarEditor")]
// com.genies.avatars.context
[assembly: InternalsVisibleTo("Genies.Avatars.Context")]
// com.genies.avatars.sdk
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk")]
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk.Editor")]
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk.Sample")]
// com.genies.avatars.services
[assembly: InternalsVisibleTo("Genies.Avatars.Services")]
[assembly: InternalsVisibleTo("Genies.Avatars.Services.Tests.Editor")]
// com.genies.closet
[assembly: InternalsVisibleTo("Genies.Closet")]
// com.genies.cloudsave
[assembly: InternalsVisibleTo("Genies.CloudSave")]
[assembly: InternalsVisibleTo("Genies.CloudSave.Tests")]
// com.genies.cms
[assembly: InternalsVisibleTo("Genies.Cms")]
[assembly: InternalsVisibleTo("Genies.Cms.AnimationLibrary")]
[assembly: InternalsVisibleTo("Genies.Cms.Animations")]
[assembly: InternalsVisibleTo("Genies.Cms.Avatars")]
[assembly: InternalsVisibleTo("Genies.Cms.Editor")]
[assembly: InternalsVisibleTo("Genies.Cms.Presets")]
[assembly: InternalsVisibleTo("Genies.Cms.ResourceLocationProvider")]
[assembly: InternalsVisibleTo("Genies.Cms.Scenes")]
[assembly: InternalsVisibleTo("Genies.Cms.Tests")]
[assembly: InternalsVisibleTo("Genies.Cms.Things")]
[assembly: InternalsVisibleTo("Genies.Cms.Traits")]
// com.genies.currency
[assembly: InternalsVisibleTo("Genies.Currency")]
[assembly: InternalsVisibleTo("Genies.Currency.Tests.Editor")]
// com.genies.experience.cloudsave
[assembly: InternalsVisibleTo("Genies.Experience.CloudSave")]
[assembly: InternalsVisibleTo("Genies.Experience.CloudSave.Tests.Editor")]
// com.genies.experience.core
[assembly: InternalsVisibleTo("DOTween.Modules.generated")]
[assembly: InternalsVisibleTo("DOTween.generated")]
[assembly: InternalsVisibleTo("Genies.Experience.Core")]
[assembly: InternalsVisibleTo("Genies.Experience.Core.generated")]
[assembly: InternalsVisibleTo("Genies.Experience.Shared.Bindings.generated")]
[assembly: InternalsVisibleTo("Genies.Naf.generated")]
[assembly: InternalsVisibleTo("Genies.Scripting.Bindings.generated")]
[assembly: InternalsVisibleTo("Genies.Sdk.Core.generated")]
[assembly: InternalsVisibleTo("LeanCommon.generated")]
[assembly: InternalsVisibleTo("LeanTouch.generated")]
[assembly: InternalsVisibleTo("UniTask.DOTween.generated")]
[assembly: InternalsVisibleTo("UniTask.generated")]
[assembly: InternalsVisibleTo("Unity.TextMeshPro.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AnimationModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AudioModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.CoreModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.IMGUIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.InputLegacyModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.ParticleSystemModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.Physics2DModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.PhysicsModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.TerrainModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.TerrainPhysicsModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.UI.generated")]
[assembly: InternalsVisibleTo("UnityEngine.UIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.VehiclesModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.WindModule.generated")]
[assembly: InternalsVisibleTo("mscorlib.generated")]
// com.genies.graphqlclient
[assembly: InternalsVisibleTo("Genies.GraphQLClient")]
// com.genies.leaderboard
[assembly: InternalsVisibleTo("Genies.Leaderboard")]
[assembly: InternalsVisibleTo("Genies.Leaderboard.Tests.Editor")]
// com.genies.login.native
[assembly: InternalsVisibleTo("Genies.Login.Native")]
[assembly: InternalsVisibleTo("Genies.Login.Native.AnonLoginSample")]
[assembly: InternalsVisibleTo("Genies.Login.Native.Editor")]
[assembly: InternalsVisibleTo("Genies.Login.Native.EmailOTPSample")]
[assembly: InternalsVisibleTo("Genies.Login.Native.EmailPasswordSample")]
[assembly: InternalsVisibleTo("Genies.Login.Native.SmsOTPV2Sample")]
[assembly: InternalsVisibleTo("Native.Login.Samples")]
// com.genies.looks
[assembly: InternalsVisibleTo("Com.Genies.Looks.Tests.Editor")]
[assembly: InternalsVisibleTo("Genies.Looks")]
// com.genies.megaeditor
[assembly: InternalsVisibleTo("Genies.MegaEditor")]
[assembly: InternalsVisibleTo("SilverStudioAvatarDemo")]
[assembly: InternalsVisibleTo("SilverStudioBase")]
[assembly: InternalsVisibleTo("SilverStudioLookDemo")]
// com.genies.multiplayer
[assembly: InternalsVisibleTo("Genies.Multiplayer")]
[assembly: InternalsVisibleTo("Genies.Multiplayer.Editor")]
// com.genies.sdk.avatar
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Editor")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Samples.AvatarStarter")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Samples.DebugSdkFunctions")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Samples.MultipleAvatars")]
// com.genies.sdk.core
[assembly: InternalsVisibleTo("Genies.Sdk.Core")]
[assembly: InternalsVisibleTo("Genies.Sdk.Core.Editor")]
// com.genies.ugc
[assembly: InternalsVisibleTo("Genies.Ugc")]
[assembly: InternalsVisibleTo("Genies.Ugc.Editor.Tests")]
// com.genies.wearable
[assembly: InternalsVisibleTo("Genies.Wearables")]
#endif
