#pragma warning disable CS0472
/* 
 * Genies Devkit API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.25
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Genies.SDKServices.Client;
using Genies.SDKServices.Model;

namespace Genies.SDKServices.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IGearApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>GearListResponse</returns>
        GearListResponse AdminGetGears (string cursor = null, decimal? limit = null);

        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>ApiResponse of GearListResponse</returns>
        ApiResponse<GearListResponse> AdminGetGearsWithHttpInfo (string cursor = null, decimal? limit = null);
        /// <summary>
        /// Create a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>GearCreateResponse</returns>
        GearCreateResponse CreateGear (GearCreateRequest body);

        /// <summary>
        /// Create a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>ApiResponse of GearCreateResponse</returns>
        ApiResponse<GearCreateResponse> CreateGearWithHttpInfo (GearCreateRequest body);
        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>GearListResponse</returns>
        GearListResponse GetGearList (string cursor = null, decimal? limit = null);

        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>ApiResponse of GearListResponse</returns>
        ApiResponse<GearListResponse> GetGearListWithHttpInfo (string cursor = null, decimal? limit = null);
        /// <summary>
        /// Get multiple gears by IDs
        /// </summary>
        /// <remarks>
        /// Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>GearGetByIdsResponse</returns>
        GearGetByIdsResponse GetGearsByIds (List<Guid?> gearIds);

        /// <summary>
        /// Get multiple gears by IDs
        /// </summary>
        /// <remarks>
        /// Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>ApiResponse of GearGetByIdsResponse</returns>
        ApiResponse<GearGetByIdsResponse> GetGearsByIdsWithHttpInfo (List<Guid?> gearIds);
        /// <summary>
        /// Pipeline get a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>GearGetByIdResponse</returns>
        GearGetByIdResponse PipelineGetGear (string gearId);

        /// <summary>
        /// Pipeline get a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of GearGetByIdResponse</returns>
        ApiResponse<GearGetByIdResponse> PipelineGetGearWithHttpInfo (string gearId);
        /// <summary>
        /// Pipeline update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>MessageResponse</returns>
        MessageResponse PipelineUpdateGear (GearUpdateRequest body, string gearId);

        /// <summary>
        /// Pipeline update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of MessageResponse</returns>
        ApiResponse<MessageResponse> PipelineUpdateGearWithHttpInfo (GearUpdateRequest body, string gearId);
        /// <summary>
        /// Update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>MessageResponse</returns>
        MessageResponse UpdateGear (GearUpdateRequest body, string gearId);

        /// <summary>
        /// Update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of MessageResponse</returns>
        ApiResponse<MessageResponse> UpdateGearWithHttpInfo (GearUpdateRequest body, string gearId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of GearListResponse</returns>
        System.Threading.Tasks.Task<GearListResponse> AdminGetGearsAsync (string cursor = null, decimal? limit = null);

        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of ApiResponse (GearListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GearListResponse>> AdminGetGearsAsyncWithHttpInfo (string cursor = null, decimal? limit = null);
        /// <summary>
        /// Create a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>Task of GearCreateResponse</returns>
        System.Threading.Tasks.Task<GearCreateResponse> CreateGearAsync (GearCreateRequest body);

        /// <summary>
        /// Create a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>Task of ApiResponse (GearCreateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GearCreateResponse>> CreateGearAsyncWithHttpInfo (GearCreateRequest body);
        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of GearListResponse</returns>
        System.Threading.Tasks.Task<GearListResponse> GetGearListAsync (string cursor = null, decimal? limit = null);

        /// <summary>
        /// Get a list of gears
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of ApiResponse (GearListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GearListResponse>> GetGearListAsyncWithHttpInfo (string cursor = null, decimal? limit = null);
        /// <summary>
        /// Get multiple gears by IDs
        /// </summary>
        /// <remarks>
        /// Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>Task of GearGetByIdsResponse</returns>
        System.Threading.Tasks.Task<GearGetByIdsResponse> GetGearsByIdsAsync (List<Guid?> gearIds);

        /// <summary>
        /// Get multiple gears by IDs
        /// </summary>
        /// <remarks>
        /// Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>Task of ApiResponse (GearGetByIdsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GearGetByIdsResponse>> GetGearsByIdsAsyncWithHttpInfo (List<Guid?> gearIds);
        /// <summary>
        /// Pipeline get a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of GearGetByIdResponse</returns>
        System.Threading.Tasks.Task<GearGetByIdResponse> PipelineGetGearAsync (string gearId);

        /// <summary>
        /// Pipeline get a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (GearGetByIdResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GearGetByIdResponse>> PipelineGetGearAsyncWithHttpInfo (string gearId);
        /// <summary>
        /// Pipeline update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of MessageResponse</returns>
        System.Threading.Tasks.Task<MessageResponse> PipelineUpdateGearAsync (GearUpdateRequest body, string gearId);

        /// <summary>
        /// Pipeline update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessageResponse>> PipelineUpdateGearAsyncWithHttpInfo (GearUpdateRequest body, string gearId);
        /// <summary>
        /// Update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of MessageResponse</returns>
        System.Threading.Tasks.Task<MessageResponse> UpdateGearAsync (GearUpdateRequest body, string gearId);

        /// <summary>
        /// Update a gear
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessageResponse>> UpdateGearAsyncWithHttpInfo (GearUpdateRequest body, string gearId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class GearApi : IGearApi
    {
        private Genies.SDKServices.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GearApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GearApi(String basePath)
        {
            this.Configuration = new Genies.SDKServices.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Genies.SDKServices.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GearApi"/> class
        /// </summary>
        /// <returns></returns>
        public GearApi()
        {
            this.Configuration = Genies.SDKServices.Client.Configuration.Default;

            ExceptionFactory = Genies.SDKServices.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GearApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GearApi(Genies.SDKServices.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Genies.SDKServices.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Genies.SDKServices.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Genies.SDKServices.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Genies.SDKServices.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>GearListResponse</returns>
        public GearListResponse AdminGetGears (string cursor = null, decimal? limit = null)
        {
             ApiResponse<GearListResponse> localVarResponse = AdminGetGearsWithHttpInfo(cursor, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>ApiResponse of GearListResponse</returns>
        public ApiResponse< GearListResponse > AdminGetGearsWithHttpInfo (string cursor = null, decimal? limit = null)
        {

            var localVarPath = "/admin/gears";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cursor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "cursor", cursor)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AdminGetGears", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearListResponse)));
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of GearListResponse</returns>
        public async System.Threading.Tasks.Task<GearListResponse> AdminGetGearsAsync (string cursor = null, decimal? limit = null)
        {
             ApiResponse<GearListResponse> localVarResponse = await AdminGetGearsAsyncWithHttpInfo(cursor, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of ApiResponse (GearListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GearListResponse>> AdminGetGearsAsyncWithHttpInfo (string cursor = null, decimal? limit = null)
        {

            var localVarPath = "/admin/gears";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cursor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "cursor", cursor)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AdminGetGears", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearListResponse)));
        }

        /// <summary>
        /// Create a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>GearCreateResponse</returns>
        public GearCreateResponse CreateGear (GearCreateRequest body)
        {
             ApiResponse<GearCreateResponse> localVarResponse = CreateGearWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>ApiResponse of GearCreateResponse</returns>
        public ApiResponse< GearCreateResponse > CreateGearWithHttpInfo (GearCreateRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->CreateGear");

            var localVarPath = "/gear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearCreateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearCreateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearCreateResponse)));
        }

        /// <summary>
        /// Create a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>Task of GearCreateResponse</returns>
        public async System.Threading.Tasks.Task<GearCreateResponse> CreateGearAsync (GearCreateRequest body)
        {
             ApiResponse<GearCreateResponse> localVarResponse = await CreateGearAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <returns>Task of ApiResponse (GearCreateResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GearCreateResponse>> CreateGearAsyncWithHttpInfo (GearCreateRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->CreateGear");

            var localVarPath = "/gear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearCreateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearCreateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearCreateResponse)));
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>GearListResponse</returns>
        public GearListResponse GetGearList (string cursor = null, decimal? limit = null)
        {
             ApiResponse<GearListResponse> localVarResponse = GetGearListWithHttpInfo(cursor, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>ApiResponse of GearListResponse</returns>
        public ApiResponse< GearListResponse > GetGearListWithHttpInfo (string cursor = null, decimal? limit = null)
        {

            var localVarPath = "/gear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cursor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "cursor", cursor)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGearList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearListResponse)));
        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of GearListResponse</returns>
        public async System.Threading.Tasks.Task<GearListResponse> GetGearListAsync (string cursor = null, decimal? limit = null)
        {
             ApiResponse<GearListResponse> localVarResponse = await GetGearListAsyncWithHttpInfo(cursor, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of gears 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">the pagination cursor (optional)</param>
        /// <param name="limit">the pagination size (optional)</param>
        /// <returns>Task of ApiResponse (GearListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GearListResponse>> GetGearListAsyncWithHttpInfo (string cursor = null, decimal? limit = null)
        {

            var localVarPath = "/gear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cursor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "cursor", cursor)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGearList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearListResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearListResponse)));
        }

        /// <summary>
        /// Get multiple gears by IDs Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>GearGetByIdsResponse</returns>
        public GearGetByIdsResponse GetGearsByIds (List<Guid?> gearIds)
        {
             ApiResponse<GearGetByIdsResponse> localVarResponse = GetGearsByIdsWithHttpInfo(gearIds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get multiple gears by IDs Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>ApiResponse of GearGetByIdsResponse</returns>
        public ApiResponse< GearGetByIdsResponse > GetGearsByIdsWithHttpInfo (List<Guid?> gearIds)
        {
            // verify the required parameter 'gearIds' is set
            if (gearIds == null)
                throw new ApiException(400, "Missing required parameter 'gearIds' when calling GearApi->GetGearsByIds");

            var localVarPath = "/gear/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "gearIds", gearIds)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGearsByIds", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearGetByIdsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearGetByIdsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearGetByIdsResponse)));
        }

        /// <summary>
        /// Get multiple gears by IDs Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>Task of GearGetByIdsResponse</returns>
        public async System.Threading.Tasks.Task<GearGetByIdsResponse> GetGearsByIdsAsync (List<Guid?> gearIds)
        {
             ApiResponse<GearGetByIdsResponse> localVarResponse = await GetGearsByIdsAsyncWithHttpInfo(gearIds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get multiple gears by IDs Retrieve multiple gear objects by their IDs in a single request. Returns only existing gears that match the provided IDs.
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearIds">Array of gear IDs to retrieve (maximum 100 IDs)</param>
        /// <returns>Task of ApiResponse (GearGetByIdsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GearGetByIdsResponse>> GetGearsByIdsAsyncWithHttpInfo (List<Guid?> gearIds)
        {
            // verify the required parameter 'gearIds' is set
            if (gearIds == null)
                throw new ApiException(400, "Missing required parameter 'gearIds' when calling GearApi->GetGearsByIds");

            var localVarPath = "/gear/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "gearIds", gearIds)); // query parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGearsByIds", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearGetByIdsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearGetByIdsResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearGetByIdsResponse)));
        }

        /// <summary>
        /// Pipeline get a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>GearGetByIdResponse</returns>
        public GearGetByIdResponse PipelineGetGear (string gearId)
        {
             ApiResponse<GearGetByIdResponse> localVarResponse = PipelineGetGearWithHttpInfo(gearId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Pipeline get a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of GearGetByIdResponse</returns>
        public ApiResponse< GearGetByIdResponse > PipelineGetGearWithHttpInfo (string gearId)
        {
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->PipelineGetGear");

            var localVarPath = "/pipeline/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            // authentication (privateToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-private-token")))
            {
                localVarHeaderParams["x-private-token"] = this.Configuration.GetApiKeyWithPrefix("x-private-token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PipelineGetGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearGetByIdResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearGetByIdResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearGetByIdResponse)));
        }

        /// <summary>
        /// Pipeline get a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of GearGetByIdResponse</returns>
        public async System.Threading.Tasks.Task<GearGetByIdResponse> PipelineGetGearAsync (string gearId)
        {
             ApiResponse<GearGetByIdResponse> localVarResponse = await PipelineGetGearAsyncWithHttpInfo(gearId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Pipeline get a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (GearGetByIdResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GearGetByIdResponse>> PipelineGetGearAsyncWithHttpInfo (string gearId)
        {
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->PipelineGetGear");

            var localVarPath = "/pipeline/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            // authentication (privateToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-private-token")))
            {
                localVarHeaderParams["x-private-token"] = this.Configuration.GetApiKeyWithPrefix("x-private-token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PipelineGetGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GearGetByIdResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GearGetByIdResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GearGetByIdResponse)));
        }

        /// <summary>
        /// Pipeline update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>MessageResponse</returns>
        public MessageResponse PipelineUpdateGear (GearUpdateRequest body, string gearId)
        {
             ApiResponse<MessageResponse> localVarResponse = PipelineUpdateGearWithHttpInfo(body, gearId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Pipeline update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of MessageResponse</returns>
        public ApiResponse< MessageResponse > PipelineUpdateGearWithHttpInfo (GearUpdateRequest body, string gearId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->PipelineUpdateGear");
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->PipelineUpdateGear");

            var localVarPath = "/pipeline/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (privateToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-private-token")))
            {
                localVarHeaderParams["x-private-token"] = this.Configuration.GetApiKeyWithPrefix("x-private-token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PipelineUpdateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MessageResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageResponse)));
        }

        /// <summary>
        /// Pipeline update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of MessageResponse</returns>
        public async System.Threading.Tasks.Task<MessageResponse> PipelineUpdateGearAsync (GearUpdateRequest body, string gearId)
        {
             ApiResponse<MessageResponse> localVarResponse = await PipelineUpdateGearAsyncWithHttpInfo(body, gearId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Pipeline update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MessageResponse>> PipelineUpdateGearAsyncWithHttpInfo (GearUpdateRequest body, string gearId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->PipelineUpdateGear");
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->PipelineUpdateGear");

            var localVarPath = "/pipeline/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (privateToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-private-token")))
            {
                localVarHeaderParams["x-private-token"] = this.Configuration.GetApiKeyWithPrefix("x-private-token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PipelineUpdateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MessageResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageResponse)));
        }

        /// <summary>
        /// Update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>MessageResponse</returns>
        public MessageResponse UpdateGear (GearUpdateRequest body, string gearId)
        {
             ApiResponse<MessageResponse> localVarResponse = UpdateGearWithHttpInfo(body, gearId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>ApiResponse of MessageResponse</returns>
        public ApiResponse< MessageResponse > UpdateGearWithHttpInfo (GearUpdateRequest body, string gearId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->UpdateGear");
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->UpdateGear");

            var localVarPath = "/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MessageResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageResponse)));
        }

        /// <summary>
        /// Update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of MessageResponse</returns>
        public async System.Threading.Tasks.Task<MessageResponse> UpdateGearAsync (GearUpdateRequest body, string gearId)
        {
             ApiResponse<MessageResponse> localVarResponse = await UpdateGearAsyncWithHttpInfo(body, gearId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update a gear 
        /// </summary>
        /// <exception cref="Genies.SDKServices.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Create gear</param>
        /// <param name="gearId">Identifier of the gear</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MessageResponse>> UpdateGearAsyncWithHttpInfo (GearUpdateRequest body, string gearId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GearApi->UpdateGear");
            // verify the required parameter 'gearId' is set
            if (gearId == null)
                throw new ApiException(400, "Missing required parameter 'gearId' when calling GearApi->UpdateGear");

            var localVarPath = "/gear/{gearId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gearId != null) localVarPathParams.Add("gearId", this.Configuration.ApiClient.ParameterToString(gearId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (clientHash) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-client-hash")))
            {
                localVarHeaderParams["x-client-hash"] = this.Configuration.GetApiKeyWithPrefix("x-client-hash");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateGear", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MessageResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageResponse)));
        }

    }
}
