//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class Entity : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Entity(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Entity obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Entity obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Entity() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnCoreWrapperPINVOKE.delete_Entity(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Entity() : this(GnCoreWrapperPINVOKE.new_Entity__SWIG_0(), true) {
  }

  public Entity(Entity other) : this(GnCoreWrapperPINVOKE.new_Entity__SWIG_1(Entity.getCPtr(other)), true) {
    if (GnCoreWrapperPINVOKE.SWIGPendingException.Pending) throw GnCoreWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsNull() {
    bool ret = GnCoreWrapperPINVOKE.Entity_IsNull(swigCPtr);
    return ret;
  }

  public string Name() {
    string ret = GnCoreWrapperPINVOKE.Entity_Name(swigCPtr);
    return ret;
  }

  public int AttributeCount() {
    int ret = GnCoreWrapperPINVOKE.Entity_AttributeCount(swigCPtr);
    return ret;
  }

  public bool Equals(Entity other) {
    bool ret = GnCoreWrapperPINVOKE.Entity_Equals(swigCPtr, Entity.getCPtr(other));
    if (GnCoreWrapperPINVOKE.SWIGPendingException.Pending) throw GnCoreWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
