//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class GnUtilsWrapper {
  public static global::System.IntPtr ForeignCallbackHandler_Void {
    set {
      GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_set(value);
    } 
    get {
      global::System.IntPtr ret = GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_get();
      return ret;
    } 
  }

  public static global::System.IntPtr ForeignCallbackHandler_Void_Bool {
    set {
      GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Bool_set(value);
    } 
    get {
      global::System.IntPtr ret = GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Bool_get();
      return ret;
    } 
  }

  public static global::System.IntPtr ForeignCallbackHandler_Void_Int {
    set {
      GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Int_set(value);
    } 
    get {
      global::System.IntPtr ret = GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Int_get();
      return ret;
    } 
  }

  public static global::System.IntPtr ForeignCallbackHandler_Void_Float {
    set {
      GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Float_set(value);
    } 
    get {
      global::System.IntPtr ret = GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_Float_get();
      return ret;
    } 
  }

  public static global::System.IntPtr ForeignCallbackHandler_Void_String {
    set {
      GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_String_set(value);
    } 
    get {
      global::System.IntPtr ret = GnUtilsWrapperPINVOKE.ForeignCallbackHandler_Void_String_get();
      return ret;
    } 
  }

}

}
