//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class LodTextureStreamingController : AssetBuilderEditor {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LodTextureStreamingController(global::System.IntPtr cPtr, bool cMemoryOwn) : base(GnCoreWrapperPINVOKE.LodTextureStreamingController_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LodTextureStreamingController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LodTextureStreamingController obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnCoreWrapperPINVOKE.delete_LodTextureStreamingController(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static LodTextureStreamingController GetFrom(AssetBuilder assetBuilder) {
    LodTextureStreamingController ret = new LodTextureStreamingController(GnCoreWrapperPINVOKE.LodTextureStreamingController_GetFrom(AssetBuilder.getCPtr(assetBuilder)), true);
    return ret;
  }

  public bool BatchLodTextureStreams() {
    bool ret = GnCoreWrapperPINVOKE.LodTextureStreamingController_BatchLodTextureStreams(swigCPtr);
    return ret;
  }

  public bool GetLoadAllLodsIfNotBatching() {
    bool ret = GnCoreWrapperPINVOKE.LodTextureStreamingController_GetLoadAllLodsIfNotBatching(swigCPtr);
    return ret;
  }

  public void SetLoadAllLodsIfNotBatching(bool value) {
    GnCoreWrapperPINVOKE.LodTextureStreamingController_SetLoadAllLodsIfNotBatching(swigCPtr, value);
  }

  public bool GetWaitForFirstLod() {
    bool ret = GnCoreWrapperPINVOKE.LodTextureStreamingController_GetWaitForFirstLod(swigCPtr);
    return ret;
  }

  public void SetWaitForFirstLod(bool value) {
    GnCoreWrapperPINVOKE.LodTextureStreamingController_SetWaitForFirstLod(swigCPtr, value);
  }

  public bool GetUpdateMaterialsOnEdit() {
    bool ret = GnCoreWrapperPINVOKE.LodTextureStreamingController_GetUpdateMaterialsOnEdit(swigCPtr);
    return ret;
  }

  public void SetUpdateMaterialsOnEdit(bool value) {
    GnCoreWrapperPINVOKE.LodTextureStreamingController_SetUpdateMaterialsOnEdit(swigCPtr, value);
  }

  public Event StreamBatchLoadedEvent() {
    global::System.IntPtr cPtr = GnCoreWrapperPINVOKE.LodTextureStreamingController_StreamBatchLoadedEvent(swigCPtr);
    Event ret = (cPtr == global::System.IntPtr.Zero) ? null : new Event(cPtr, true);
    return ret;
  }

  public Event AllStreamsLoadedEvent() {
    global::System.IntPtr cPtr = GnCoreWrapperPINVOKE.LodTextureStreamingController_AllStreamsLoadedEvent(swigCPtr);
    Event ret = (cPtr == global::System.IntPtr.Zero) ? null : new Event(cPtr, true);
    return ret;
  }

  public static LodTextureStreamingController Create(AssetBuilder assetBuilder, bool batchLodTextureStreams) {
    LodTextureStreamingController ret = new LodTextureStreamingController(GnCoreWrapperPINVOKE.LodTextureStreamingController_Create(AssetBuilder.getCPtr(assetBuilder), batchLodTextureStreams), true);
    return ret;
  }

  public LodTextureStreamingController() : this(GnCoreWrapperPINVOKE.new_LodTextureStreamingController(), true) {
  }

}

}
