//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class OzzFloat4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OzzFloat4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OzzFloat4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OzzFloat4 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OzzFloat4() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnAnimationWrapperPINVOKE.delete_OzzFloat4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OzzFloat4() : this(GnAnimationWrapperPINVOKE.new_OzzFloat4(), true) {
  }

  public float x {
    set {
      GnAnimationWrapperPINVOKE.OzzFloat4_x_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzFloat4_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      GnAnimationWrapperPINVOKE.OzzFloat4_y_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzFloat4_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      GnAnimationWrapperPINVOKE.OzzFloat4_z_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzFloat4_z_get(swigCPtr);
      return ret;
    } 
  }

  public float w {
    set {
      GnAnimationWrapperPINVOKE.OzzFloat4_w_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzFloat4_w_get(swigCPtr);
      return ret;
    } 
  }

}

}
