//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class OzzSoaTransform : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OzzSoaTransform(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OzzSoaTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OzzSoaTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OzzSoaTransform() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnAnimationWrapperPINVOKE.delete_OzzSoaTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OzzSoaTransform() : this(GnAnimationWrapperPINVOKE.new_OzzSoaTransform(), true) {
  }

  public float translationX0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX0_get(swigCPtr);
      return ret;
    } 
  }

  public float translationX1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX1_get(swigCPtr);
      return ret;
    } 
  }

  public float translationX2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX2_get(swigCPtr);
      return ret;
    } 
  }

  public float translationX3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationX3_get(swigCPtr);
      return ret;
    } 
  }

  public float translationY0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY0_get(swigCPtr);
      return ret;
    } 
  }

  public float translationY1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY1_get(swigCPtr);
      return ret;
    } 
  }

  public float translationY2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY2_get(swigCPtr);
      return ret;
    } 
  }

  public float translationY3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationY3_get(swigCPtr);
      return ret;
    } 
  }

  public float translationZ0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ0_get(swigCPtr);
      return ret;
    } 
  }

  public float translationZ1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ1_get(swigCPtr);
      return ret;
    } 
  }

  public float translationZ2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ2_get(swigCPtr);
      return ret;
    } 
  }

  public float translationZ3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_translationZ3_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationX0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX0_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationX1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX1_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationX2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX2_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationX3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationX3_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationY0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY0_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationY1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY1_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationY2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY2_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationY3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationY3_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationZ0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ0_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationZ1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ1_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationZ2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ2_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationZ3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationZ3_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationW0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW0_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationW1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW1_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationW2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW2_get(swigCPtr);
      return ret;
    } 
  }

  public float rotationW3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_rotationW3_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleX0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX0_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleX1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX1_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleX2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX2_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleX3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleX3_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleY0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY0_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleY1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY1_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleY2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY2_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleY3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleY3_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleZ0 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ0_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ0_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleZ1 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ1_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ1_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleZ2 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ2_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ2_get(swigCPtr);
      return ret;
    } 
  }

  public float scaleZ3 {
    set {
      GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ3_set(swigCPtr, value);
    } 
    get {
      float ret = GnAnimationWrapperPINVOKE.OzzSoaTransform_scaleZ3_get(swigCPtr);
      return ret;
    } 
  }

}

}
