//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class VectorInt16 : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<short>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorInt16(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorInt16 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorInt16 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorInt16() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnAnimationWrapperPINVOKE.delete_VectorInt16(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorInt16(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (short element in c) {
      this.Add(element);
    }
  }

  public VectorInt16(global::System.Collections.Generic.IEnumerable<short> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (short element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public short this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(short[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(short[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, short[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public short[] ToArray() {
    short[] array = new short[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<short> global::System.Collections.Generic.IEnumerable<short>.GetEnumerator() {
    return new VectorInt16Enumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorInt16Enumerator(this);
  }

  public VectorInt16Enumerator GetEnumerator() {
    return new VectorInt16Enumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorInt16Enumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<short>
  {
    private VectorInt16 collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorInt16Enumerator(VectorInt16 collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public short Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (short)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorInt16() : this(GnAnimationWrapperPINVOKE.new_VectorInt16__SWIG_0(), true) {
  }

  public VectorInt16(VectorInt16 other) : this(GnAnimationWrapperPINVOKE.new_VectorInt16__SWIG_1(VectorInt16.getCPtr(other)), true) {
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    GnAnimationWrapperPINVOKE.VectorInt16_Clear(swigCPtr);
  }

  public void Add(short x) {
    GnAnimationWrapperPINVOKE.VectorInt16_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = GnAnimationWrapperPINVOKE.VectorInt16_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = GnAnimationWrapperPINVOKE.VectorInt16_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = GnAnimationWrapperPINVOKE.VectorInt16_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    GnAnimationWrapperPINVOKE.VectorInt16_reserve(swigCPtr, n);
  }

  public VectorInt16(int capacity) : this(GnAnimationWrapperPINVOKE.new_VectorInt16__SWIG_2(capacity), true) {
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  private short getitemcopy(int index) {
    short ret = GnAnimationWrapperPINVOKE.VectorInt16_getitemcopy(swigCPtr, index);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private short getitem(int index) {
    short ret = GnAnimationWrapperPINVOKE.VectorInt16_getitem(swigCPtr, index);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, short val) {
    GnAnimationWrapperPINVOKE.VectorInt16_setitem(swigCPtr, index, val);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorInt16 values) {
    GnAnimationWrapperPINVOKE.VectorInt16_AddRange(swigCPtr, VectorInt16.getCPtr(values));
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorInt16 GetRange(int index, int count) {
    global::System.IntPtr cPtr = GnAnimationWrapperPINVOKE.VectorInt16_GetRange(swigCPtr, index, count);
    VectorInt16 ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorInt16(cPtr, true);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, short x) {
    GnAnimationWrapperPINVOKE.VectorInt16_Insert(swigCPtr, index, x);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorInt16 values) {
    GnAnimationWrapperPINVOKE.VectorInt16_InsertRange(swigCPtr, index, VectorInt16.getCPtr(values));
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    GnAnimationWrapperPINVOKE.VectorInt16_RemoveAt(swigCPtr, index);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    GnAnimationWrapperPINVOKE.VectorInt16_RemoveRange(swigCPtr, index, count);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorInt16 Repeat(short value, int count) {
    global::System.IntPtr cPtr = GnAnimationWrapperPINVOKE.VectorInt16_Repeat(value, count);
    VectorInt16 ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorInt16(cPtr, true);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    GnAnimationWrapperPINVOKE.VectorInt16_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    GnAnimationWrapperPINVOKE.VectorInt16_Reverse__SWIG_1(swigCPtr, index, count);
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorInt16 values) {
    GnAnimationWrapperPINVOKE.VectorInt16_SetRange(swigCPtr, index, VectorInt16.getCPtr(values));
    if (GnAnimationWrapperPINVOKE.SWIGPendingException.Pending) throw GnAnimationWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(short value) {
    bool ret = GnAnimationWrapperPINVOKE.VectorInt16_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(short value) {
    int ret = GnAnimationWrapperPINVOKE.VectorInt16_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(short value) {
    int ret = GnAnimationWrapperPINVOKE.VectorInt16_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(short value) {
    bool ret = GnAnimationWrapperPINVOKE.VectorInt16_Remove(swigCPtr, value);
    return ret;
  }

}

}
