//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class VectorAnimationFormat : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<AnimationFormat>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorAnimationFormat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorAnimationFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorAnimationFormat obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorAnimationFormat() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnContainerWrapperPINVOKE.delete_VectorAnimationFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorAnimationFormat(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (AnimationFormat element in c) {
      this.Add(element);
    }
  }

  public VectorAnimationFormat(global::System.Collections.Generic.IEnumerable<AnimationFormat> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (AnimationFormat element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public AnimationFormat this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(AnimationFormat[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(AnimationFormat[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, AnimationFormat[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public AnimationFormat[] ToArray() {
    AnimationFormat[] array = new AnimationFormat[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<AnimationFormat> global::System.Collections.Generic.IEnumerable<AnimationFormat>.GetEnumerator() {
    return new VectorAnimationFormatEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorAnimationFormatEnumerator(this);
  }

  public VectorAnimationFormatEnumerator GetEnumerator() {
    return new VectorAnimationFormatEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorAnimationFormatEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<AnimationFormat>
  {
    private VectorAnimationFormat collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorAnimationFormatEnumerator(VectorAnimationFormat collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public AnimationFormat Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (AnimationFormat)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorAnimationFormat() : this(GnContainerWrapperPINVOKE.new_VectorAnimationFormat__SWIG_0(), true) {
  }

  public VectorAnimationFormat(VectorAnimationFormat other) : this(GnContainerWrapperPINVOKE.new_VectorAnimationFormat__SWIG_1(VectorAnimationFormat.getCPtr(other)), true) {
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_Clear(swigCPtr);
  }

  public void Add(AnimationFormat x) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_Add(swigCPtr, (int)x);
  }

  private uint size() {
    uint ret = GnContainerWrapperPINVOKE.VectorAnimationFormat_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = GnContainerWrapperPINVOKE.VectorAnimationFormat_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = GnContainerWrapperPINVOKE.VectorAnimationFormat_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_reserve(swigCPtr, n);
  }

  public VectorAnimationFormat(int capacity) : this(GnContainerWrapperPINVOKE.new_VectorAnimationFormat__SWIG_2(capacity), true) {
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  private AnimationFormat getitemcopy(int index) {
    AnimationFormat ret = (AnimationFormat)GnContainerWrapperPINVOKE.VectorAnimationFormat_getitemcopy(swigCPtr, index);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private AnimationFormat getitem(int index) {
    AnimationFormat ret = (AnimationFormat)GnContainerWrapperPINVOKE.VectorAnimationFormat_getitem(swigCPtr, index);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, AnimationFormat val) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_setitem(swigCPtr, index, (int)val);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorAnimationFormat values) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_AddRange(swigCPtr, VectorAnimationFormat.getCPtr(values));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorAnimationFormat GetRange(int index, int count) {
    global::System.IntPtr cPtr = GnContainerWrapperPINVOKE.VectorAnimationFormat_GetRange(swigCPtr, index, count);
    VectorAnimationFormat ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorAnimationFormat(cPtr, true);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, AnimationFormat x) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_Insert(swigCPtr, index, (int)x);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorAnimationFormat values) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_InsertRange(swigCPtr, index, VectorAnimationFormat.getCPtr(values));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_RemoveAt(swigCPtr, index);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_RemoveRange(swigCPtr, index, count);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorAnimationFormat Repeat(AnimationFormat value, int count) {
    global::System.IntPtr cPtr = GnContainerWrapperPINVOKE.VectorAnimationFormat_Repeat((int)value, count);
    VectorAnimationFormat ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorAnimationFormat(cPtr, true);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_Reverse__SWIG_1(swigCPtr, index, count);
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorAnimationFormat values) {
    GnContainerWrapperPINVOKE.VectorAnimationFormat_SetRange(swigCPtr, index, VectorAnimationFormat.getCPtr(values));
    if (GnContainerWrapperPINVOKE.SWIGPendingException.Pending) throw GnContainerWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
