//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class VertexAttributeAccessors : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VertexAttributeAccessors(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VertexAttributeAccessors obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VertexAttributeAccessors obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VertexAttributeAccessors() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnCoreWrapperPINVOKE.delete_VertexAttributeAccessors(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DynamicAccessor Get(uint entryIndex) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_0(swigCPtr, entryIndex), true);
    return ret;
  }

  public DynamicAccessor Get(string entryName) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_1(swigCPtr, entryName), true);
    return ret;
  }

  public DynamicAccessor Get(StandardVertexAttribute attribute, uint channelIndex) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_2(swigCPtr, (int)attribute, channelIndex), true);
    return ret;
  }

  public DynamicAccessor Get(StandardVertexAttribute attribute) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_3(swigCPtr, (int)attribute), true);
    return ret;
  }

  public DynamicAccessor Get(VertexAttribute attribute, uint channelIndex) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_4(swigCPtr, VertexAttribute.getCPtr(attribute), channelIndex), true);
    return ret;
  }

  public DynamicAccessor Get(VertexAttribute attribute) {
    DynamicAccessor ret = new DynamicAccessor(GnCoreWrapperPINVOKE.VertexAttributeAccessors_Get__SWIG_5(swigCPtr, VertexAttribute.getCPtr(attribute)), true);
    return ret;
  }

  public bool Contains(uint entryIndex) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_0(swigCPtr, entryIndex);
    return ret;
  }

  public bool Contains(string entryName) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_1(swigCPtr, entryName);
    return ret;
  }

  public bool Contains(StandardVertexAttribute attribute, uint channelIndex) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_2(swigCPtr, (int)attribute, channelIndex);
    return ret;
  }

  public bool Contains(StandardVertexAttribute attribute) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_3(swigCPtr, (int)attribute);
    return ret;
  }

  public bool Contains(VertexAttribute attribute, uint channelIndex) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_4(swigCPtr, VertexAttribute.getCPtr(attribute), channelIndex);
    return ret;
  }

  public bool Contains(VertexAttribute attribute) {
    bool ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Contains__SWIG_5(swigCPtr, VertexAttribute.getCPtr(attribute));
    return ret;
  }

  public uint Size() {
    uint ret = GnCoreWrapperPINVOKE.VertexAttributeAccessors_Size(swigCPtr);
    return ret;
  }

  public VectorSizeT GetSetAttributes() {
    VectorSizeT ret = new VectorSizeT(GnCoreWrapperPINVOKE.VertexAttributeAccessors_GetSetAttributes(swigCPtr), true);
    return ret;
  }

  public VertexAttributeAccessors() : this(GnCoreWrapperPINVOKE.new_VertexAttributeAccessors(), true) {
  }

}

}
