//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GnWrappers {

public class VoidFuture : Future {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VoidFuture(global::System.IntPtr cPtr, bool cMemoryOwn) : base(GnUtilsWrapperPINVOKE.VoidFuture_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VoidFuture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VoidFuture obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GnUtilsWrapperPINVOKE.delete_VoidFuture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public VoidFuture() : this(GnUtilsWrapperPINVOKE.new_VoidFuture(), true) {
  }

  public override bool IsValid() {
    bool ret = GnUtilsWrapperPINVOKE.VoidFuture_IsValid(swigCPtr);
    return ret;
  }

  public override bool IsReady() {
    bool ret = GnUtilsWrapperPINVOKE.VoidFuture_IsReady(swigCPtr);
    if (GnUtilsWrapperPINVOKE.SWIGPendingException.Pending) throw GnUtilsWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void Wait() {
    GnUtilsWrapperPINVOKE.VoidFuture_Wait(swigCPtr);
    if (GnUtilsWrapperPINVOKE.SWIGPendingException.Pending) throw GnUtilsWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool WaitFor(uint milliseconds) {
    bool ret = GnUtilsWrapperPINVOKE.VoidFuture_WaitFor(swigCPtr, milliseconds);
    return ret;
  }

  public void Get() {
    GnUtilsWrapperPINVOKE.VoidFuture_Get(swigCPtr);
    if (GnUtilsWrapperPINVOKE.SWIGPendingException.Pending) throw GnUtilsWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VoidFuture Completed() {
    VoidFuture ret = new VoidFuture(GnUtilsWrapperPINVOKE.VoidFuture_Completed(), true);
    return ret;
  }

}

}
