#pragma warning disable CS0472
/*
 * Genies Devkit API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.25
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.SDKServices.Client.SwaggerDateConverter;
namespace Genies.SDKServices.Model
{
    /// <summary>
    /// Representation of response body for create gear
    /// </summary>
    [DataContract]
        public partial class GearCreateResponse :  IEquatable<GearCreateResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GearCreateResponse" /> class.
        /// </summary>
        /// <param name="gearId">gearId.</param>
        /// <param name="gearVersionId">gearVersionId.</param>
        /// <param name="presignedUrl">presignedUrl.</param>
        public GearCreateResponse(string gearId = default(string), string gearVersionId = default(string), string presignedUrl = default(string))
        {
            this.GearId = gearId;
            this.GearVersionId = gearVersionId;
            this.PresignedUrl = presignedUrl;
        }

        /// <summary>
        /// Gets or Sets GearId
        /// </summary>
        [DataMember(Name="gearId", EmitDefaultValue=false)]
        public string GearId { get; set; }

        /// <summary>
        /// Gets or Sets GearVersionId
        /// </summary>
        [DataMember(Name="gearVersionId", EmitDefaultValue=false)]
        public string GearVersionId { get; set; }

        /// <summary>
        /// Gets or Sets PresignedUrl
        /// </summary>
        [DataMember(Name="presignedUrl", EmitDefaultValue=false)]
        public string PresignedUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GearCreateResponse {\n");
            sb.Append("  GearId: ").Append(GearId).Append("\n");
            sb.Append("  GearVersionId: ").Append(GearVersionId).Append("\n");
            sb.Append("  PresignedUrl: ").Append(PresignedUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GearCreateResponse);
        }

        /// <summary>
        /// Returns true if GearCreateResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GearCreateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GearCreateResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    this.GearId == input.GearId ||
                    (this.GearId != null &&
                    this.GearId.Equals(input.GearId))
                ) &&
                (
                    this.GearVersionId == input.GearVersionId ||
                    (this.GearVersionId != null &&
                    this.GearVersionId.Equals(input.GearVersionId))
                ) &&
                (
                    this.PresignedUrl == input.PresignedUrl ||
                    (this.PresignedUrl != null &&
                    this.PresignedUrl.Equals(input.PresignedUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GearId != null)
                    hashCode = hashCode * 59 + this.GearId.GetHashCode();
                if (this.GearVersionId != null)
                    hashCode = hashCode * 59 + this.GearVersionId.GetHashCode();
                if (this.PresignedUrl != null)
                    hashCode = hashCode * 59 + this.PresignedUrl.GetHashCode();
                return hashCode;
            }
        }
    }
}
