#pragma warning disable CS0472
/*
 * Genies Devkit API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.25
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.SDKServices.Client.SwaggerDateConverter;
namespace Genies.SDKServices.Model
{
    /// <summary>
    /// List of gear objects
    /// </summary>
    [DataContract]
        public partial class GearListResponse :  IEquatable<GearListResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GearListResponse" /> class.
        /// </summary>
        /// <param name="gears">gears.</param>
        /// <param name="cursor">cursor.</param>
        public GearListResponse(List<Gear> gears = default(List<Gear>), string cursor = default(string))
        {
            this.Gears = gears;
            this.Cursor = cursor;
        }

        /// <summary>
        /// Gets or Sets Gears
        /// </summary>
        [DataMember(Name="gears", EmitDefaultValue=false)]
        public List<Gear> Gears { get; set; }

        /// <summary>
        /// Gets or Sets Cursor
        /// </summary>
        [DataMember(Name="cursor", EmitDefaultValue=false)]
        public string Cursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GearListResponse {\n");
            sb.Append("  Gears: ").Append(Gears).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GearListResponse);
        }

        /// <summary>
        /// Returns true if GearListResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GearListResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GearListResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Gears == input.Gears ||
                    this.Gears != null &&
                    input.Gears != null &&
                    this.Gears.SequenceEqual(input.Gears)
                ) &&
                (
                    this.Cursor == input.Cursor ||
                    (this.Cursor != null &&
                    this.Cursor.Equals(input.Cursor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gears != null)
                    hashCode = hashCode * 59 + this.Gears.GetHashCode();
                if (this.Cursor != null)
                    hashCode = hashCode * 59 + this.Cursor.GetHashCode();
                return hashCode;
            }
        }
    }
}
