#pragma warning disable CS0472
/*
 * Genies Devkit API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.25
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.SDKServices.Client.SwaggerDateConverter;
namespace Genies.SDKServices.Model
{
    /// <summary>
    /// LeaderboardGetResponse
    /// </summary>
    [DataContract]
        public partial class LeaderboardGetResponse :  IEquatable<LeaderboardGetResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardGetResponse" /> class.
        /// </summary>
        /// <param name="leaderboards">leaderboards.</param>
        /// <param name="nextCursor">nextCursor.</param>
        public LeaderboardGetResponse(List<Leaderboard> leaderboards = default(List<Leaderboard>), string nextCursor = default(string))
        {
            this.Leaderboards = leaderboards;
            this.NextCursor = nextCursor;
        }

        /// <summary>
        /// Gets or Sets Leaderboards
        /// </summary>
        [DataMember(Name="leaderboards", EmitDefaultValue=false)]
        public List<Leaderboard> Leaderboards { get; set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [DataMember(Name="nextCursor", EmitDefaultValue=false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LeaderboardGetResponse {\n");
            sb.Append("  Leaderboards: ").Append(Leaderboards).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeaderboardGetResponse);
        }

        /// <summary>
        /// Returns true if LeaderboardGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LeaderboardGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeaderboardGetResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Leaderboards == input.Leaderboards ||
                    this.Leaderboards != null &&
                    input.Leaderboards != null &&
                    this.Leaderboards.SequenceEqual(input.Leaderboards)
                ) &&
                (
                    this.NextCursor == input.NextCursor ||
                    (this.NextCursor != null &&
                    this.NextCursor.Equals(input.NextCursor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Leaderboards != null)
                    hashCode = hashCode * 59 + this.Leaderboards.GetHashCode();
                if (this.NextCursor != null)
                    hashCode = hashCode * 59 + this.NextCursor.GetHashCode();
                return hashCode;
            }
        }
    }
}
