#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// ActivitiesResponse
    /// </summary>
    [DataContract]
        public partial class ActivitiesResponse :  IEquatable<ActivitiesResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivitiesResponse" /> class.
        /// </summary>
        /// <param name="activities">activities.</param>
        public ActivitiesResponse(List<ActivitiesResponseActivities> activities = default(List<ActivitiesResponseActivities>))
        {
            this.Activities = activities;
        }
        
        /// <summary>
        /// Gets or Sets Activities
        /// </summary>
        [DataMember(Name="activities", EmitDefaultValue=false)]
        public List<ActivitiesResponseActivities> Activities { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ActivitiesResponse {\n");
            sb.Append("  Activities: ").Append(Activities).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ActivitiesResponse);
        }

        /// <summary>
        /// Returns true if ActivitiesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ActivitiesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActivitiesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Activities == input.Activities ||
                    this.Activities != null &&
                    input.Activities != null &&
                    this.Activities.SequenceEqual(input.Activities)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Activities != null)
                    hashCode = hashCode * 59 + this.Activities.GetHashCode();
                return hashCode;
            }
        }
    }
}
