#pragma warning disable CS0472
/*
 * Genies Mobile API
 *
 * Genies Composer server.
 *
 * OpenAPI spec version: 1.3.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;

namespace Genies.Services.Model
{
    /// <summary>
    /// AllOfUserContactResponseContactsItems
    /// </summary>
    [DataContract]
        public partial class AllOfUserContactResponseContactsItems : UserContact,  IEquatable<AllOfUserContactResponseContactsItems>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AllOfUserContactResponseContactsItems" /> class.
        /// </summary>
        public AllOfUserContactResponseContactsItems(string username = default(string), string phoneNumber = default(string), string firstName = default(string), string lastName = default(string)) : base(username, phoneNumber, firstName, lastName)
        {
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AllOfUserContactResponseContactsItems {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AllOfUserContactResponseContactsItems);
        }

        /// <summary>
        /// Returns true if AllOfUserContactResponseContactsItems instances are equal
        /// </summary>
        /// <param name="input">Instance of AllOfUserContactResponseContactsItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AllOfUserContactResponseContactsItems input)
        {
            if (input == null)
                return false;

            return base.Equals(input);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }
    }
}
