#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents an individual avatar.
    /// </summary>
    [DataContract]
        public partial class Avatar :  IEquatable<Avatar>
    {
        /// <summary>
        /// Placeholder status values 
        /// </summary>
        /// <value>Placeholder status values </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum Disabled for value: disabled
            /// </summary>
            [EnumMember(Value = "disabled")]
            Disabled = 1,
            /// <summary>
            /// Enum Hidden for value: hidden
            /// </summary>
            [EnumMember(Value = "hidden")]
            Hidden = 2,
            /// <summary>
            /// Enum Visible for value: visible
            /// </summary>
            [EnumMember(Value = "visible")]
            Visible = 3        }
        /// <summary>
        /// Placeholder status values 
        /// </summary>
        /// <value>Placeholder status values </value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Avatar gender:  * &#x60;male&#x60;  * &#x60;female&#x60;  * &#x60;nonbinary&#x60; 
        /// </summary>
        /// <value>Avatar gender:  * &#x60;male&#x60;  * &#x60;female&#x60;  * &#x60;nonbinary&#x60; </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum GenderEnum
        {
            /// <summary>
            /// Enum Male for value: male
            /// </summary>
            [EnumMember(Value = "male")]
            Male = 1,
            /// <summary>
            /// Enum Female for value: female
            /// </summary>
            [EnumMember(Value = "female")]
            Female = 2,
            /// <summary>
            /// Enum Nonbinary for value: nonbinary
            /// </summary>
            [EnumMember(Value = "nonbinary")]
            Nonbinary = 3        }
        /// <summary>
        /// Avatar gender:  * &#x60;male&#x60;  * &#x60;female&#x60;  * &#x60;nonbinary&#x60; 
        /// </summary>
        /// <value>Avatar gender:  * &#x60;male&#x60;  * &#x60;female&#x60;  * &#x60;nonbinary&#x60; </value>
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public GenderEnum? Gender { get; set; }
        /// <summary>
        /// Type of avatar definition:  * &#x60;normal&#x60; - regular avatar definition as managed by the composer app  * &#x60;vip&#x60; - special avatar definition with limited editing available 
        /// </summary>
        /// <value>Type of avatar definition:  * &#x60;normal&#x60; - regular avatar definition as managed by the composer app  * &#x60;vip&#x60; - special avatar definition with limited editing available </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum DefTypeEnum
        {
            /// <summary>
            /// Enum Normal for value: normal
            /// </summary>
            [EnumMember(Value = "normal")]
            Normal = 1,
            /// <summary>
            /// Enum Vip for value: vip
            /// </summary>
            [EnumMember(Value = "vip")]
            Vip = 2        }
        /// <summary>
        /// Type of avatar definition:  * &#x60;normal&#x60; - regular avatar definition as managed by the composer app  * &#x60;vip&#x60; - special avatar definition with limited editing available 
        /// </summary>
        /// <value>Type of avatar definition:  * &#x60;normal&#x60; - regular avatar definition as managed by the composer app  * &#x60;vip&#x60; - special avatar definition with limited editing available </value>
        [DataMember(Name="defType", EmitDefaultValue=false)]
        public DefTypeEnum? DefType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Avatar" /> class.
        /// </summary>
        /// <param name="userId">User UUID.</param>
        /// <param name="status">Placeholder status values .</param>
        /// <param name="gender">Avatar gender:  * &#x60;male&#x60;  * &#x60;female&#x60;  * &#x60;nonbinary&#x60; .</param>
        /// <param name="defType">Type of avatar definition:  * &#x60;normal&#x60; - regular avatar definition as managed by the composer app  * &#x60;vip&#x60; - special avatar definition with limited editing available .</param>
        /// <param name="definition">JSON data describing the construction of the avatar .</param>
        /// <param name="lodUrl">cloudfront url that points to the low res avatar.</param>
        public Avatar(string userId = default(string), StatusEnum? status = default(StatusEnum?), GenderEnum? gender = default(GenderEnum?), DefTypeEnum? defType = default(DefTypeEnum?), string definition = default(string), string lodUrl = default(string))
        {
            this.UserId = userId;
            this.Status = status;
            this.Gender = gender;
            this.DefType = defType;
            this.Definition = definition;
            this.LodUrl = lodUrl;
        }
        
        /// <summary>
        /// Avatar UUID
        /// </summary>
        /// <value>Avatar UUID</value>
        [DataMember(Name="avatarId", EmitDefaultValue=false)]
        public string AvatarId { get; private set; }

        /// <summary>
        /// User UUID
        /// </summary>
        /// <value>User UUID</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public int? Created { get; private set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="lastModified", EmitDefaultValue=false)]
        public int? LastModified { get; private set; }




        /// <summary>
        /// JSON data describing the construction of the avatar 
        /// </summary>
        /// <value>JSON data describing the construction of the avatar </value>
        [DataMember(Name="definition", EmitDefaultValue=false)]
        public string Definition { get; set; }

        /// <summary>
        /// cloudfront url that points to the low res avatar
        /// </summary>
        /// <value>cloudfront url that points to the low res avatar</value>
        [DataMember(Name="lodUrl", EmitDefaultValue=false)]
        public string LodUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Avatar {\n");
            sb.Append("  AvatarId: ").Append(AvatarId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  DefType: ").Append(DefType).Append("\n");
            sb.Append("  Definition: ").Append(Definition).Append("\n");
            sb.Append("  LodUrl: ").Append(LodUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Avatar);
        }

        /// <summary>
        /// Returns true if Avatar instances are equal
        /// </summary>
        /// <param name="input">Instance of Avatar to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Avatar input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AvatarId == input.AvatarId ||
                    (this.AvatarId != null &&
                    this.AvatarId.Equals(input.AvatarId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Gender == input.Gender ||
                    (this.Gender != null &&
                    this.Gender.Equals(input.Gender))
                ) && 
                (
                    this.DefType == input.DefType ||
                    (this.DefType != null &&
                    this.DefType.Equals(input.DefType))
                ) && 
                (
                    this.Definition == input.Definition ||
                    (this.Definition != null &&
                    this.Definition.Equals(input.Definition))
                ) && 
                (
                    this.LodUrl == input.LodUrl ||
                    (this.LodUrl != null &&
                    this.LodUrl.Equals(input.LodUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AvatarId != null)
                    hashCode = hashCode * 59 + this.AvatarId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Gender != null)
                    hashCode = hashCode * 59 + this.Gender.GetHashCode();
                if (this.DefType != null)
                    hashCode = hashCode * 59 + this.DefType.GetHashCode();
                if (this.Definition != null)
                    hashCode = hashCode * 59 + this.Definition.GetHashCode();
                if (this.LodUrl != null)
                    hashCode = hashCode * 59 + this.LodUrl.GetHashCode();
                return hashCode;
            }
        }
    }
}
