#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// ClosetItemGears
    /// </summary>
    [DataContract]
        public partial class ClosetItemGears :  IEquatable<ClosetItemGears>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClosetItemGears" /> class.
        /// </summary>
        /// <param name="gearId">gearId.</param>
        /// <param name="latestVersionId">latestVersionId.</param>
        public ClosetItemGears(string gearId = default(string), string latestVersionId = default(string))
        {
            this.GearId = gearId;
            this.LatestVersionId = latestVersionId;
        }
        
        /// <summary>
        /// Gets or Sets GearId
        /// </summary>
        [DataMember(Name="gearId", EmitDefaultValue=false)]
        public string GearId { get; set; }

        /// <summary>
        /// Gets or Sets LatestVersionId
        /// </summary>
        [DataMember(Name="latestVersionId", EmitDefaultValue=false)]
        public string LatestVersionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClosetItemGears {\n");
            sb.Append("  GearId: ").Append(GearId).Append("\n");
            sb.Append("  LatestVersionId: ").Append(LatestVersionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClosetItemGears);
        }

        /// <summary>
        /// Returns true if ClosetItemGears instances are equal
        /// </summary>
        /// <param name="input">Instance of ClosetItemGears to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClosetItemGears input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GearId == input.GearId ||
                    (this.GearId != null &&
                    this.GearId.Equals(input.GearId))
                ) && 
                (
                    this.LatestVersionId == input.LatestVersionId ||
                    (this.LatestVersionId != null &&
                    this.LatestVersionId.Equals(input.LatestVersionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GearId != null)
                    hashCode = hashCode * 59 + this.GearId.GetHashCode();
                if (this.LatestVersionId != null)
                    hashCode = hashCode * 59 + this.LatestVersionId.GetHashCode();
                return hashCode;
            }
        }
    }
}
