#pragma warning disable CS0472
/*
 * Genies Mobile API
 *
 * Genies Composer server.
 *
 * OpenAPI spec version: 1.9.59
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// List of Daily Quest objects
    /// </summary>
    [DataContract]
        public partial class DailyQuestList :  IEquatable<DailyQuestList>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DailyQuestList" /> class.
        /// </summary>
        /// <param name="quests">quests.</param>
        public DailyQuestList(List<DailyQuest> quests = default(List<DailyQuest>))
        {
            this.Quests = quests;
        }

        /// <summary>
        /// Gets or Sets Quests
        /// </summary>
        [DataMember(Name="quests", EmitDefaultValue=false)]
        public List<DailyQuest> Quests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DailyQuestList {\n");
            sb.Append("  Quests: ").Append(Quests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DailyQuestList);
        }

        /// <summary>
        /// Returns true if DailyQuestList instances are equal
        /// </summary>
        /// <param name="input">Instance of DailyQuestList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DailyQuestList input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Quests == input.Quests ||
                    this.Quests != null &&
                    input.Quests != null &&
                    this.Quests.SequenceEqual(input.Quests)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Quests != null)
                    hashCode = hashCode * 59 + this.Quests.GetHashCode();
                return hashCode;
            }
        }
    }
}
