#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Daily Quest for the user
    /// </summary>
    [DataContract]
        public partial class DailyQuest :  IEquatable<DailyQuest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DailyQuest" /> class.
        /// </summary>
        /// <param name="questId">questId.</param>
        /// <param name="goal">goal.</param>
        /// <param name="action">action.</param>
        /// <param name="category">category.</param>
        /// <param name="title">title.</param>
        /// <param name="currencyReward">currencyReward.</param>
        /// <param name="version">version.</param>
        /// <param name="description">description.</param>
        /// <param name="expiration">expiration.</param>
        public DailyQuest(string questId = default(string), decimal? goal = default(decimal?), string action = default(string), string category = default(string), string title = default(string), decimal? currencyReward = default(decimal?), string version = default(string), string description = default(string), decimal? expiration = default(decimal?))
        {
            this.QuestId = questId;
            this.Goal = goal;
            this.Action = action;
            this.Category = category;
            this.Title = title;
            this.CurrencyReward = currencyReward;
            this.Version = version;
            this.Description = description;
            this.Expiration = expiration;
        }
        
        /// <summary>
        /// Gets or Sets QuestId
        /// </summary>
        [DataMember(Name="questId", EmitDefaultValue=false)]
        public string QuestId { get; set; }

        /// <summary>
        /// Gets or Sets Goal
        /// </summary>
        [DataMember(Name="goal", EmitDefaultValue=false)]
        public decimal? Goal { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyReward
        /// </summary>
        [DataMember(Name="currencyReward", EmitDefaultValue=false)]
        public decimal? CurrencyReward { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Expiration
        /// </summary>
        [DataMember(Name="expiration", EmitDefaultValue=false)]
        public decimal? Expiration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DailyQuest {\n");
            sb.Append("  QuestId: ").Append(QuestId).Append("\n");
            sb.Append("  Goal: ").Append(Goal).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  CurrencyReward: ").Append(CurrencyReward).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DailyQuest);
        }

        /// <summary>
        /// Returns true if DailyQuest instances are equal
        /// </summary>
        /// <param name="input">Instance of DailyQuest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DailyQuest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuestId == input.QuestId ||
                    (this.QuestId != null &&
                    this.QuestId.Equals(input.QuestId))
                ) && 
                (
                    this.Goal == input.Goal ||
                    (this.Goal != null &&
                    this.Goal.Equals(input.Goal))
                ) && 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.CurrencyReward == input.CurrencyReward ||
                    (this.CurrencyReward != null &&
                    this.CurrencyReward.Equals(input.CurrencyReward))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Expiration == input.Expiration ||
                    (this.Expiration != null &&
                    this.Expiration.Equals(input.Expiration))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuestId != null)
                    hashCode = hashCode * 59 + this.QuestId.GetHashCode();
                if (this.Goal != null)
                    hashCode = hashCode * 59 + this.Goal.GetHashCode();
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.CurrencyReward != null)
                    hashCode = hashCode * 59 + this.CurrencyReward.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Expiration != null)
                    hashCode = hashCode * 59 + this.Expiration.GetHashCode();
                return hashCode;
            }
        }
    }
}
