#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents the feed object response.
    /// </summary>
    [DataContract]
        public partial class FeedSaveResponse :  IEquatable<FeedSaveResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedSaveResponse" /> class.
        /// </summary>
        /// <param name="feedId">Feed unique identifier.</param>
        /// <param name="senderId">The user who sent the save.</param>
        /// <param name="receiverId">The user who made the feed and who&#x27;s feed is being saved.</param>
        /// <param name="senderUsername">The username of the sender who saved the feed,.</param>
        /// <param name="created">Epoch time of creation.</param>
        public FeedSaveResponse(string feedId = default(string), string senderId = default(string), string receiverId = default(string), string senderUsername = default(string), decimal? created = default(decimal?))
        {
            this.FeedId = feedId;
            this.SenderId = senderId;
            this.ReceiverId = receiverId;
            this.SenderUsername = senderUsername;
            this.Created = created;
        }
        
        /// <summary>
        /// Feed unique identifier
        /// </summary>
        /// <value>Feed unique identifier</value>
        [DataMember(Name="feedId", EmitDefaultValue=false)]
        public string FeedId { get; set; }

        /// <summary>
        /// The user who sent the save
        /// </summary>
        /// <value>The user who sent the save</value>
        [DataMember(Name="senderId", EmitDefaultValue=false)]
        public string SenderId { get; set; }

        /// <summary>
        /// The user who made the feed and who&#x27;s feed is being saved
        /// </summary>
        /// <value>The user who made the feed and who&#x27;s feed is being saved</value>
        [DataMember(Name="receiverId", EmitDefaultValue=false)]
        public string ReceiverId { get; set; }

        /// <summary>
        /// The username of the sender who saved the feed,
        /// </summary>
        /// <value>The username of the sender who saved the feed,</value>
        [DataMember(Name="senderUsername", EmitDefaultValue=false)]
        public string SenderUsername { get; set; }

        /// <summary>
        /// Epoch time of creation
        /// </summary>
        /// <value>Epoch time of creation</value>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public decimal? Created { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FeedSaveResponse {\n");
            sb.Append("  FeedId: ").Append(FeedId).Append("\n");
            sb.Append("  SenderId: ").Append(SenderId).Append("\n");
            sb.Append("  ReceiverId: ").Append(ReceiverId).Append("\n");
            sb.Append("  SenderUsername: ").Append(SenderUsername).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FeedSaveResponse);
        }

        /// <summary>
        /// Returns true if FeedSaveResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of FeedSaveResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FeedSaveResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FeedId == input.FeedId ||
                    (this.FeedId != null &&
                    this.FeedId.Equals(input.FeedId))
                ) && 
                (
                    this.SenderId == input.SenderId ||
                    (this.SenderId != null &&
                    this.SenderId.Equals(input.SenderId))
                ) && 
                (
                    this.ReceiverId == input.ReceiverId ||
                    (this.ReceiverId != null &&
                    this.ReceiverId.Equals(input.ReceiverId))
                ) && 
                (
                    this.SenderUsername == input.SenderUsername ||
                    (this.SenderUsername != null &&
                    this.SenderUsername.Equals(input.SenderUsername))
                ) && 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FeedId != null)
                    hashCode = hashCode * 59 + this.FeedId.GetHashCode();
                if (this.SenderId != null)
                    hashCode = hashCode * 59 + this.SenderId.GetHashCode();
                if (this.ReceiverId != null)
                    hashCode = hashCode * 59 + this.ReceiverId.GetHashCode();
                if (this.SenderUsername != null)
                    hashCode = hashCode * 59 + this.SenderUsername.GetHashCode();
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                return hashCode;
            }
        }
    }
}
