#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Response containing quest progress for the user
    /// </summary>
    [DataContract]
        public partial class GetQuestProgressResponse :  IEquatable<GetQuestProgressResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetQuestProgressResponse" /> class.
        /// </summary>
        /// <param name="progress">Array of quest progress entries.</param>
        public GetQuestProgressResponse(List<QuestProgress> progress = default(List<QuestProgress>))
        {
            this.Progress = progress;
        }
        
        /// <summary>
        /// Array of quest progress entries
        /// </summary>
        /// <value>Array of quest progress entries</value>
        [DataMember(Name="progress", EmitDefaultValue=false)]
        public List<QuestProgress> Progress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetQuestProgressResponse {\n");
            sb.Append("  Progress: ").Append(Progress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetQuestProgressResponse);
        }

        /// <summary>
        /// Returns true if GetQuestProgressResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetQuestProgressResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetQuestProgressResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Progress == input.Progress ||
                    this.Progress != null &&
                    input.Progress != null &&
                    this.Progress.SequenceEqual(input.Progress)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Progress != null)
                    hashCode = hashCode * 59 + this.Progress.GetHashCode();
                return hashCode;
            }
        }
    }
}
