#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// GetStorefrontResponse
    /// </summary>
    [DataContract]
        public partial class GetStorefrontResponse :  IEquatable<GetStorefrontResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStorefrontResponse" /> class.
        /// </summary>
        /// <param name="hardCurrencyProducts">hardCurrencyProducts.</param>
        public GetStorefrontResponse(List<HardCurrencyProductStorefront> hardCurrencyProducts = default(List<HardCurrencyProductStorefront>))
        {
            this.HardCurrencyProducts = hardCurrencyProducts;
        }
        
        /// <summary>
        /// Gets or Sets HardCurrencyProducts
        /// </summary>
        [DataMember(Name="hardCurrencyProducts", EmitDefaultValue=false)]
        public List<HardCurrencyProductStorefront> HardCurrencyProducts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetStorefrontResponse {\n");
            sb.Append("  HardCurrencyProducts: ").Append(HardCurrencyProducts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetStorefrontResponse);
        }

        /// <summary>
        /// Returns true if GetStorefrontResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetStorefrontResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStorefrontResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HardCurrencyProducts == input.HardCurrencyProducts ||
                    this.HardCurrencyProducts != null &&
                    input.HardCurrencyProducts != null &&
                    this.HardCurrencyProducts.SequenceEqual(input.HardCurrencyProducts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HardCurrencyProducts != null)
                    hashCode = hashCode * 59 + this.HardCurrencyProducts.GetHashCode();
                return hashCode;
            }
        }
    }
}
