#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Response object of the invites sent
    /// </summary>
    [DataContract]
        public partial class InvitesSentResponse :  IEquatable<InvitesSentResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvitesSentResponse" /> class.
        /// </summary>
        /// <param name="invites">invites.</param>
        public InvitesSentResponse(List<InvitesSent> invites = default(List<InvitesSent>))
        {
            this.Invites = invites;
        }
        
        /// <summary>
        /// Gets or Sets Invites
        /// </summary>
        [DataMember(Name="invites", EmitDefaultValue=false)]
        public List<InvitesSent> Invites { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvitesSentResponse {\n");
            sb.Append("  Invites: ").Append(Invites).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InvitesSentResponse);
        }

        /// <summary>
        /// Returns true if InvitesSentResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of InvitesSentResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvitesSentResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Invites == input.Invites ||
                    this.Invites != null &&
                    input.Invites != null &&
                    this.Invites.SequenceEqual(input.Invites)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Invites != null)
                    hashCode = hashCode * 59 + this.Invites.GetHashCode();
                return hashCode;
            }
        }
    }
}
