#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents request to update a look.
    /// </summary>
    [DataContract]
        public partial class LookUpdate :  IEquatable<LookUpdate>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LookUpdate" /> class.
        /// </summary>
        /// <param name="animationId">Addressable id for the animation.</param>
        /// <param name="dollDefinition">Definition for the doll, similar to avatarDefinition.</param>
        /// <param name="sceneId">Addressable id for the scene.</param>
        /// <param name="avatarDefinition">Definition for the avatar.</param>
        /// <param name="exportedAt">Timestamp the look was shared/exported.</param>
        /// <param name="thumbnail">URL for the thumbnail image of the look.</param>
        /// <param name="videoClip">URL for the video clip of the look.</param>
        public LookUpdate(string animationId = default(string), string dollDefinition = default(string), string sceneId = default(string), string avatarDefinition = default(string), decimal? exportedAt = default(decimal?), string thumbnail = default(string), string videoClip = default(string))
        {
            this.AnimationId = animationId;
            this.DollDefinition = dollDefinition;
            this.SceneId = sceneId;
            this.AvatarDefinition = avatarDefinition;
            this.ExportedAt = exportedAt;
            this.Thumbnail = thumbnail;
            this.VideoClip = videoClip;
        }
        
        /// <summary>
        /// Addressable id for the animation
        /// </summary>
        /// <value>Addressable id for the animation</value>
        [DataMember(Name="animationId", EmitDefaultValue=false)]
        public string AnimationId { get; set; }

        /// <summary>
        /// Definition for the doll, similar to avatarDefinition
        /// </summary>
        /// <value>Definition for the doll, similar to avatarDefinition</value>
        [DataMember(Name="dollDefinition", EmitDefaultValue=false)]
        public string DollDefinition { get; set; }

        /// <summary>
        /// Addressable id for the scene
        /// </summary>
        /// <value>Addressable id for the scene</value>
        [DataMember(Name="sceneId", EmitDefaultValue=false)]
        public string SceneId { get; set; }

        /// <summary>
        /// Definition for the avatar
        /// </summary>
        /// <value>Definition for the avatar</value>
        [DataMember(Name="avatarDefinition", EmitDefaultValue=false)]
        public string AvatarDefinition { get; set; }

        /// <summary>
        /// Timestamp the look was shared/exported
        /// </summary>
        /// <value>Timestamp the look was shared/exported</value>
        [DataMember(Name="exportedAt", EmitDefaultValue=false)]
        public decimal? ExportedAt { get; set; }

        /// <summary>
        /// URL for the thumbnail image of the look
        /// </summary>
        /// <value>URL for the thumbnail image of the look</value>
        [DataMember(Name="thumbnail", EmitDefaultValue=false)]
        public string Thumbnail { get; set; }

        /// <summary>
        /// URL for the video clip of the look
        /// </summary>
        /// <value>URL for the video clip of the look</value>
        [DataMember(Name="videoClip", EmitDefaultValue=false)]
        public string VideoClip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LookUpdate {\n");
            sb.Append("  AnimationId: ").Append(AnimationId).Append("\n");
            sb.Append("  DollDefinition: ").Append(DollDefinition).Append("\n");
            sb.Append("  SceneId: ").Append(SceneId).Append("\n");
            sb.Append("  AvatarDefinition: ").Append(AvatarDefinition).Append("\n");
            sb.Append("  ExportedAt: ").Append(ExportedAt).Append("\n");
            sb.Append("  Thumbnail: ").Append(Thumbnail).Append("\n");
            sb.Append("  VideoClip: ").Append(VideoClip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LookUpdate);
        }

        /// <summary>
        /// Returns true if LookUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of LookUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LookUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AnimationId == input.AnimationId ||
                    (this.AnimationId != null &&
                    this.AnimationId.Equals(input.AnimationId))
                ) && 
                (
                    this.DollDefinition == input.DollDefinition ||
                    (this.DollDefinition != null &&
                    this.DollDefinition.Equals(input.DollDefinition))
                ) && 
                (
                    this.SceneId == input.SceneId ||
                    (this.SceneId != null &&
                    this.SceneId.Equals(input.SceneId))
                ) && 
                (
                    this.AvatarDefinition == input.AvatarDefinition ||
                    (this.AvatarDefinition != null &&
                    this.AvatarDefinition.Equals(input.AvatarDefinition))
                ) && 
                (
                    this.ExportedAt == input.ExportedAt ||
                    (this.ExportedAt != null &&
                    this.ExportedAt.Equals(input.ExportedAt))
                ) && 
                (
                    this.Thumbnail == input.Thumbnail ||
                    (this.Thumbnail != null &&
                    this.Thumbnail.Equals(input.Thumbnail))
                ) && 
                (
                    this.VideoClip == input.VideoClip ||
                    (this.VideoClip != null &&
                    this.VideoClip.Equals(input.VideoClip))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AnimationId != null)
                    hashCode = hashCode * 59 + this.AnimationId.GetHashCode();
                if (this.DollDefinition != null)
                    hashCode = hashCode * 59 + this.DollDefinition.GetHashCode();
                if (this.SceneId != null)
                    hashCode = hashCode * 59 + this.SceneId.GetHashCode();
                if (this.AvatarDefinition != null)
                    hashCode = hashCode * 59 + this.AvatarDefinition.GetHashCode();
                if (this.ExportedAt != null)
                    hashCode = hashCode * 59 + this.ExportedAt.GetHashCode();
                if (this.Thumbnail != null)
                    hashCode = hashCode * 59 + this.Thumbnail.GetHashCode();
                if (this.VideoClip != null)
                    hashCode = hashCode * 59 + this.VideoClip.GetHashCode();
                return hashCode;
            }
        }
    }
}
