#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Mood
    /// </summary>
    [DataContract]
        public partial class MoodResponse :  IEquatable<MoodResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoodResponse" /> class.
        /// </summary>
        /// <param name="moodExists">moodExists.</param>
        /// <param name="mood">mood.</param>
        /// <param name="moodType">moodType.</param>
        public MoodResponse(bool? moodExists = default(bool?), string mood = default(string), string moodType = default(string))
        {
            this.MoodExists = moodExists;
            this.Mood = mood;
            this.MoodType = moodType;
        }
        
        /// <summary>
        /// Gets or Sets MoodExists
        /// </summary>
        [DataMember(Name="moodExists", EmitDefaultValue=false)]
        public bool? MoodExists { get; set; }

        /// <summary>
        /// Gets or Sets Mood
        /// </summary>
        [DataMember(Name="mood", EmitDefaultValue=false)]
        public string Mood { get; set; }

        /// <summary>
        /// Gets or Sets MoodType
        /// </summary>
        [DataMember(Name="moodType", EmitDefaultValue=false)]
        public string MoodType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MoodResponse {\n");
            sb.Append("  MoodExists: ").Append(MoodExists).Append("\n");
            sb.Append("  Mood: ").Append(Mood).Append("\n");
            sb.Append("  MoodType: ").Append(MoodType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MoodResponse);
        }

        /// <summary>
        /// Returns true if MoodResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MoodResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MoodResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MoodExists == input.MoodExists ||
                    (this.MoodExists != null &&
                    this.MoodExists.Equals(input.MoodExists))
                ) && 
                (
                    this.Mood == input.Mood ||
                    (this.Mood != null &&
                    this.Mood.Equals(input.Mood))
                ) && 
                (
                    this.MoodType == input.MoodType ||
                    (this.MoodType != null &&
                    this.MoodType.Equals(input.MoodType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MoodExists != null)
                    hashCode = hashCode * 59 + this.MoodExists.GetHashCode();
                if (this.Mood != null)
                    hashCode = hashCode * 59 + this.Mood.GetHashCode();
                if (this.MoodType != null)
                    hashCode = hashCode * 59 + this.MoodType.GetHashCode();
                return hashCode;
            }
        }
    }
}
