#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// SendMessageByFCMTokenRequest
    /// </summary>
    [DataContract]
        public partial class SendMessageByFCMTokenRequest :  IEquatable<SendMessageByFCMTokenRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessageByFCMTokenRequest" /> class.
        /// </summary>
        /// <param name="tokens">List of the token, max length is 10.</param>
        /// <param name="title">Message title (required).</param>
        /// <param name="message">Message content (required).</param>
        public SendMessageByFCMTokenRequest(List<string> tokens = default(List<string>), string title = default(string), string message = default(string))
        {
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new InvalidDataException("title is a required property for SendMessageByFCMTokenRequest and cannot be null");
            }
            else
            {
                this.Title = title;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for SendMessageByFCMTokenRequest and cannot be null");
            }
            else
            {
                this.Message = message;
            }
            this.Tokens = tokens;
        }
        
        /// <summary>
        /// List of the token, max length is 10
        /// </summary>
        /// <value>List of the token, max length is 10</value>
        [DataMember(Name="tokens", EmitDefaultValue=false)]
        public List<string> Tokens { get; set; }

        /// <summary>
        /// Message title
        /// </summary>
        /// <value>Message title</value>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Message content
        /// </summary>
        /// <value>Message content</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SendMessageByFCMTokenRequest {\n");
            sb.Append("  Tokens: ").Append(Tokens).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SendMessageByFCMTokenRequest);
        }

        /// <summary>
        /// Returns true if SendMessageByFCMTokenRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SendMessageByFCMTokenRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SendMessageByFCMTokenRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Tokens == input.Tokens ||
                    this.Tokens != null &&
                    input.Tokens != null &&
                    this.Tokens.SequenceEqual(input.Tokens)
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Tokens != null)
                    hashCode = hashCode * 59 + this.Tokens.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }
    }
}
