#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// SoftCurrencyProductStorefront
    /// </summary>
    [DataContract]
        public partial class SoftCurrencyProductStorefront :  IEquatable<SoftCurrencyProductStorefront>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SoftCurrencyProductStorefront" /> class.
        /// </summary>
        /// <param name="productSku">productSku.</param>
        /// <param name="title">title.</param>
        /// <param name="description">description.</param>
        /// <param name="iconUrl">iconUrl.</param>
        /// <param name="amount">amount.</param>
        /// <param name="hcCost">hcCost.</param>
        public SoftCurrencyProductStorefront(string productSku = default(string), string title = default(string), string description = default(string), string iconUrl = default(string), long? amount = default(long?), long? hcCost = default(long?))
        {
            this.ProductSku = productSku;
            this.Title = title;
            this.Description = description;
            this.IconUrl = iconUrl;
            this.Amount = amount;
            this.HcCost = hcCost;
        }
        
        /// <summary>
        /// Gets or Sets ProductSku
        /// </summary>
        [DataMember(Name="productSku", EmitDefaultValue=false)]
        public string ProductSku { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets IconUrl
        /// </summary>
        [DataMember(Name="iconUrl", EmitDefaultValue=false)]
        public string IconUrl { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public long? Amount { get; set; }

        /// <summary>
        /// Gets or Sets HcCost
        /// </summary>
        [DataMember(Name="hcCost", EmitDefaultValue=false)]
        public long? HcCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SoftCurrencyProductStorefront {\n");
            sb.Append("  ProductSku: ").Append(ProductSku).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IconUrl: ").Append(IconUrl).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  HcCost: ").Append(HcCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SoftCurrencyProductStorefront);
        }

        /// <summary>
        /// Returns true if SoftCurrencyProductStorefront instances are equal
        /// </summary>
        /// <param name="input">Instance of SoftCurrencyProductStorefront to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SoftCurrencyProductStorefront input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProductSku == input.ProductSku ||
                    (this.ProductSku != null &&
                    this.ProductSku.Equals(input.ProductSku))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.IconUrl == input.IconUrl ||
                    (this.IconUrl != null &&
                    this.IconUrl.Equals(input.IconUrl))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.HcCost == input.HcCost ||
                    (this.HcCost != null &&
                    this.HcCost.Equals(input.HcCost))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductSku != null)
                    hashCode = hashCode * 59 + this.ProductSku.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.IconUrl != null)
                    hashCode = hashCode * 59 + this.IconUrl.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.HcCost != null)
                    hashCode = hashCode * 59 + this.HcCost.GetHashCode();
                return hashCode;
            }
        }
    }
}
