#pragma warning disable CS0472
/*
 * Genies Mobile API
 *
 * Genies Composer server.
 *
 * OpenAPI spec version: 1.8.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// SpaceReactions
    /// </summary>
    [DataContract]
        public partial class SpaceReactions :  IEquatable<SpaceReactions>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpaceReactions" /> class.
        /// </summary>
        /// <param name="reactions">reactions.</param>
        /// <param name="nextCursor">nextCursor.</param>
        public SpaceReactions(List<SpaceReaction> reactions = default(List<SpaceReaction>), string nextCursor = default(string))
        {
            this.Reactions = reactions;
            this.NextCursor = nextCursor;
        }

        /// <summary>
        /// Gets or Sets Reactions
        /// </summary>
        [DataMember(Name="reactions", EmitDefaultValue=false)]
        public List<SpaceReaction> Reactions { get; set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [DataMember(Name="nextCursor", EmitDefaultValue=false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpaceReactions {\n");
            sb.Append("  Reactions: ").Append(Reactions).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpaceReactions);
        }

        /// <summary>
        /// Returns true if SpaceReactions instances are equal
        /// </summary>
        /// <param name="input">Instance of SpaceReactions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpaceReactions input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Reactions == input.Reactions ||
                    this.Reactions != null &&
                    input.Reactions != null &&
                    this.Reactions.SequenceEqual(input.Reactions)
                ) &&
                (
                    this.NextCursor == input.NextCursor ||
                    (this.NextCursor != null &&
                    this.NextCursor.Equals(input.NextCursor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Reactions != null)
                    hashCode = hashCode * 59 + this.Reactions.GetHashCode();
                if (this.NextCursor != null)
                    hashCode = hashCode * 59 + this.NextCursor.GetHashCode();
                return hashCode;
            }
        }
    }
}
