#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Request body for updating an existing custom color preset
    /// </summary>
    [DataContract]
        public partial class UpdateCustomColorRequest :  IEquatable<UpdateCustomColorRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCustomColorRequest" /> class.
        /// </summary>
        /// <param name="colorsHex">Updated array of hex color values.</param>
        /// <param name="name">Updated display name.</param>
        public UpdateCustomColorRequest(List<string> colorsHex = default(List<string>), string name = default(string))
        {
            this.ColorsHex = colorsHex;
            this.Name = name;
        }
        
        /// <summary>
        /// Updated array of hex color values
        /// </summary>
        /// <value>Updated array of hex color values</value>
        [DataMember(Name="colorsHex", EmitDefaultValue=false)]
        public List<string> ColorsHex { get; set; }

        /// <summary>
        /// Updated display name
        /// </summary>
        /// <value>Updated display name</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateCustomColorRequest {\n");
            sb.Append("  ColorsHex: ").Append(ColorsHex).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateCustomColorRequest);
        }

        /// <summary>
        /// Returns true if UpdateCustomColorRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateCustomColorRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCustomColorRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ColorsHex == input.ColorsHex ||
                    this.ColorsHex != null &&
                    input.ColorsHex != null &&
                    this.ColorsHex.SequenceEqual(input.ColorsHex)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ColorsHex != null)
                    hashCode = hashCode * 59 + this.ColorsHex.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }
    }
}
