#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents a single user to compare
    /// </summary>
    [DataContract]
        public partial class UserComparison :  IEquatable<UserComparison>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserComparison" /> class.
        /// </summary>
        /// <param name="userId">Unique identifier for the user from cognito.</param>
        /// <param name="username">User defined username for them (preferred username from cognito).</param>
        /// <param name="firstName">User defined first name.</param>
        /// <param name="lastName">User defined last name.</param>
        public UserComparison(string userId = default(string), string username = default(string), string firstName = default(string), string lastName = default(string))
        {
            this.UserId = userId;
            this.Username = username;
            this.FirstName = firstName;
            this.LastName = lastName;
        }
        
        /// <summary>
        /// Unique identifier for the user from cognito
        /// </summary>
        /// <value>Unique identifier for the user from cognito</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public string UserId { get; set; }

        /// <summary>
        /// User defined username for them (preferred username from cognito)
        /// </summary>
        /// <value>User defined username for them (preferred username from cognito)</value>
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// User defined first name
        /// </summary>
        /// <value>User defined first name</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// User defined last name
        /// </summary>
        /// <value>User defined last name</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserComparison {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserComparison);
        }

        /// <summary>
        /// Returns true if UserComparison instances are equal
        /// </summary>
        /// <param name="input">Instance of UserComparison to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserComparison input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                return hashCode;
            }
        }
    }
}
