#pragma warning disable CS0472
/*
 * Genies Mobile API
 *
 * Genies Composer server.
 *
 * OpenAPI spec version: 1.6.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents the response to the user&#x27;s count stats
    /// </summary>
    [DataContract]
        public partial class UserCountResponse :  IEquatable<UserCountResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCountResponse" /> class.
        /// </summary>
        /// <param name="counts">List of counts that the user has received.</param>
        public UserCountResponse(List<CountUser> counts = default(List<CountUser>))
        {
            this.Counts = counts;
        }

        /// <summary>
        /// List of counts that the user has received
        /// </summary>
        /// <value>List of counts that the user has received</value>
        [DataMember(Name="counts", EmitDefaultValue=false)]
        public List<CountUser> Counts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserCountResponse {\n");
            sb.Append("  Counts: ").Append(Counts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserCountResponse);
        }

        /// <summary>
        /// Returns true if UserCountResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of UserCountResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserCountResponse input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Counts == input.Counts ||
                    this.Counts != null &&
                    input.Counts != null &&
                    this.Counts.SequenceEqual(input.Counts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Counts != null)
                    hashCode = hashCode * 59 + this.Counts.GetHashCode();
                return hashCode;
            }
        }
    }
}
