#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents response of a pending user invite
    /// </summary>
    [DataContract]
        public partial class UserPending :  IEquatable<UserPending>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserPending" /> class.
        /// </summary>
        /// <param name="inviteId">Unique id of the invitation.</param>
        /// <param name="inviteeId">UserId of the user who received the invite.</param>
        /// <param name="inviteePhoneNumber">Phone number of user to generate invite link for.</param>
        /// <param name="updatedAt">Time of invitation creation.</param>
        public UserPending(string inviteId = default(string), string inviteeId = default(string), string inviteePhoneNumber = default(string), decimal? updatedAt = default(decimal?))
        {
            this.InviteId = inviteId;
            this.InviteeId = inviteeId;
            this.InviteePhoneNumber = inviteePhoneNumber;
            this.UpdatedAt = updatedAt;
        }
        
        /// <summary>
        /// Unique id of the invitation
        /// </summary>
        /// <value>Unique id of the invitation</value>
        [DataMember(Name="inviteId", EmitDefaultValue=false)]
        public string InviteId { get; set; }

        /// <summary>
        /// UserId of the user who received the invite
        /// </summary>
        /// <value>UserId of the user who received the invite</value>
        [DataMember(Name="inviteeId", EmitDefaultValue=false)]
        public string InviteeId { get; set; }

        /// <summary>
        /// Phone number of user to generate invite link for
        /// </summary>
        /// <value>Phone number of user to generate invite link for</value>
        [DataMember(Name="inviteePhoneNumber", EmitDefaultValue=false)]
        public string InviteePhoneNumber { get; set; }

        /// <summary>
        /// Time of invitation creation
        /// </summary>
        /// <value>Time of invitation creation</value>
        [DataMember(Name="updatedAt", EmitDefaultValue=false)]
        public decimal? UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserPending {\n");
            sb.Append("  InviteId: ").Append(InviteId).Append("\n");
            sb.Append("  InviteeId: ").Append(InviteeId).Append("\n");
            sb.Append("  InviteePhoneNumber: ").Append(InviteePhoneNumber).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserPending);
        }

        /// <summary>
        /// Returns true if UserPending instances are equal
        /// </summary>
        /// <param name="input">Instance of UserPending to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserPending input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InviteId == input.InviteId ||
                    (this.InviteId != null &&
                    this.InviteId.Equals(input.InviteId))
                ) && 
                (
                    this.InviteeId == input.InviteeId ||
                    (this.InviteeId != null &&
                    this.InviteeId.Equals(input.InviteeId))
                ) && 
                (
                    this.InviteePhoneNumber == input.InviteePhoneNumber ||
                    (this.InviteePhoneNumber != null &&
                    this.InviteePhoneNumber.Equals(input.InviteePhoneNumber))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InviteId != null)
                    hashCode = hashCode * 59 + this.InviteId.GetHashCode();
                if (this.InviteeId != null)
                    hashCode = hashCode * 59 + this.InviteeId.GetHashCode();
                if (this.InviteePhoneNumber != null)
                    hashCode = hashCode * 59 + this.InviteePhoneNumber.GetHashCode();
                if (this.UpdatedAt != null)
                    hashCode = hashCode * 59 + this.UpdatedAt.GetHashCode();
                return hashCode;
            }
        }
    }
}
