#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Flattened VersionableInventoryAsset schema
    /// </summary>
    [DataContract]
        public partial class VersionableInventoryAsset :  IEquatable<VersionableInventoryAsset>
    {
        /// <summary>
        /// Type of the asset
        /// </summary>
        /// <value>Type of the asset</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum AssetTypeEnum
        {
            /// <summary>
            /// Enum WardrobeGear for value: WardrobeGear
            /// </summary>
            [EnumMember(Value = "WardrobeGear")]
            WardrobeGear = 1,
            /// <summary>
            /// Enum ModelLibrary for value: ModelLibrary
            /// </summary>
            [EnumMember(Value = "ModelLibrary")]
            ModelLibrary = 2,
            /// <summary>
            /// Enum UserAvatar for value: UserAvatar
            /// </summary>
            [EnumMember(Value = "UserAvatar")]
            UserAvatar = 3,
            /// <summary>
            /// Enum SubSpecies for value: SubSpecies
            /// </summary>
            [EnumMember(Value = "SubSpecies")]
            SubSpecies = 4,
            /// <summary>
            /// Enum AvatarBase for value: AvatarBase
            /// </summary>
            [EnumMember(Value = "AvatarBase")]
            AvatarBase = 5,
            /// <summary>
            /// Enum AvatarMakeup for value: AvatarMakeup
            /// </summary>
            [EnumMember(Value = "AvatarMakeup")]
            AvatarMakeup = 6,
            /// <summary>
            /// Enum Flair for value: Flair
            /// </summary>
            [EnumMember(Value = "Flair")]
            Flair = 7,
            /// <summary>
            /// Enum AvatarEyes for value: AvatarEyes
            /// </summary>
            [EnumMember(Value = "AvatarEyes")]
            AvatarEyes = 8,
            /// <summary>
            /// Enum ColorPreset for value: ColorPreset
            /// </summary>
            [EnumMember(Value = "ColorPreset")]
            ColorPreset = 9,
            /// <summary>
            /// Enum ImageLibrary for value: ImageLibrary
            /// </summary>
            [EnumMember(Value = "ImageLibrary")]
            ImageLibrary = 10,
            /// <summary>
            /// Enum AnimationLibrary for value: AnimationLibrary
            /// </summary>
            [EnumMember(Value = "AnimationLibrary")]
            AnimationLibrary = 11        }
        /// <summary>
        /// Type of the asset
        /// </summary>
        /// <value>Type of the asset</value>
        [DataMember(Name="assetType", EmitDefaultValue=false)]
        public AssetTypeEnum? AssetType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionableInventoryAsset" /> class.
        /// </summary>
        /// <param name="assetId">Unique identifier for the asset type.</param>
        /// <param name="assetType">Type of the asset.</param>
        /// <param name="name">Display name of the asset.</param>
        /// <param name="description">Short description of the asset.</param>
        /// <param name="longDescription">Detailed description of the asset.</param>
        /// <param name="orgId">Organization ID.</param>
        /// <param name="appId">Application ID.</param>
        /// <param name="order">Ordering for display.</param>
        /// <param name="creator">Creator of the asset.</param>
        /// <param name="pipeline">Pipeline information for the asset (V2 format with string versions and pipeline ID).</param>
        public VersionableInventoryAsset(string assetId = default(string), AssetTypeEnum? assetType = default(AssetTypeEnum?), string name = default(string), string description = default(string), string longDescription = default(string), string orgId = default(string), string appId = default(string), int? order = default(int?), string creator = default(string), List<PipelineItemV2> pipeline = default(List<PipelineItemV2>))
        {
            this.AssetId = assetId;
            this.AssetType = assetType;
            this.Name = name;
            this.Description = description;
            this.LongDescription = longDescription;
            this.OrgId = orgId;
            this.AppId = appId;
            this.Order = order;
            this.Creator = creator;
            this.Pipeline = pipeline;
        }
        
        /// <summary>
        /// Unique identifier for the asset type
        /// </summary>
        /// <value>Unique identifier for the asset type</value>
        [DataMember(Name="assetId", EmitDefaultValue=false)]
        public string AssetId { get; set; }


        /// <summary>
        /// Display name of the asset
        /// </summary>
        /// <value>Display name of the asset</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Short description of the asset
        /// </summary>
        /// <value>Short description of the asset</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Detailed description of the asset
        /// </summary>
        /// <value>Detailed description of the asset</value>
        [DataMember(Name="longDescription", EmitDefaultValue=false)]
        public string LongDescription { get; set; }

        /// <summary>
        /// Organization ID
        /// </summary>
        /// <value>Organization ID</value>
        [DataMember(Name="orgId", EmitDefaultValue=false)]
        public string OrgId { get; set; }

        /// <summary>
        /// Application ID
        /// </summary>
        /// <value>Application ID</value>
        [DataMember(Name="appId", EmitDefaultValue=false)]
        public string AppId { get; set; }

        /// <summary>
        /// Ordering for display
        /// </summary>
        /// <value>Ordering for display</value>
        [DataMember(Name="order", EmitDefaultValue=false)]
        public int? Order { get; set; }

        /// <summary>
        /// Creator of the asset
        /// </summary>
        /// <value>Creator of the asset</value>
        [DataMember(Name="creator", EmitDefaultValue=false)]
        public string Creator { get; set; }

        /// <summary>
        /// Pipeline information for the asset (V2 format with string versions and pipeline ID)
        /// </summary>
        /// <value>Pipeline information for the asset (V2 format with string versions and pipeline ID)</value>
        [DataMember(Name="pipeline", EmitDefaultValue=false)]
        public List<PipelineItemV2> Pipeline { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VersionableInventoryAsset {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  AssetType: ").Append(AssetType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  LongDescription: ").Append(LongDescription).Append("\n");
            sb.Append("  OrgId: ").Append(OrgId).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Creator: ").Append(Creator).Append("\n");
            sb.Append("  Pipeline: ").Append(Pipeline).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VersionableInventoryAsset);
        }

        /// <summary>
        /// Returns true if VersionableInventoryAsset instances are equal
        /// </summary>
        /// <param name="input">Instance of VersionableInventoryAsset to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VersionableInventoryAsset input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                ) && 
                (
                    this.AssetType == input.AssetType ||
                    (this.AssetType != null &&
                    this.AssetType.Equals(input.AssetType))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.LongDescription == input.LongDescription ||
                    (this.LongDescription != null &&
                    this.LongDescription.Equals(input.LongDescription))
                ) && 
                (
                    this.OrgId == input.OrgId ||
                    (this.OrgId != null &&
                    this.OrgId.Equals(input.OrgId))
                ) && 
                (
                    this.AppId == input.AppId ||
                    (this.AppId != null &&
                    this.AppId.Equals(input.AppId))
                ) && 
                (
                    this.Order == input.Order ||
                    (this.Order != null &&
                    this.Order.Equals(input.Order))
                ) && 
                (
                    this.Creator == input.Creator ||
                    (this.Creator != null &&
                    this.Creator.Equals(input.Creator))
                ) && 
                (
                    this.Pipeline == input.Pipeline ||
                    this.Pipeline != null &&
                    input.Pipeline != null &&
                    this.Pipeline.SequenceEqual(input.Pipeline)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetId != null)
                    hashCode = hashCode * 59 + this.AssetId.GetHashCode();
                if (this.AssetType != null)
                    hashCode = hashCode * 59 + this.AssetType.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.LongDescription != null)
                    hashCode = hashCode * 59 + this.LongDescription.GetHashCode();
                if (this.OrgId != null)
                    hashCode = hashCode * 59 + this.OrgId.GetHashCode();
                if (this.AppId != null)
                    hashCode = hashCode * 59 + this.AppId.GetHashCode();
                if (this.Order != null)
                    hashCode = hashCode * 59 + this.Order.GetHashCode();
                if (this.Creator != null)
                    hashCode = hashCode * 59 + this.Creator.GetHashCode();
                if (this.Pipeline != null)
                    hashCode = hashCode * 59 + this.Pipeline.GetHashCode();
                return hashCode;
            }
        }
    }
}
