#pragma warning disable CS0472
/* 
 * Genies Mobile API
 *
 * Genies Composer server. 
 *
 * OpenAPI spec version: 1.9.92
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Services.Client.SwaggerDateConverter;
namespace Genies.Services.Model
{
    /// <summary>
    /// Represents an individual wearable.
    /// </summary>
    [DataContract]
        public partial class Wearable :  IEquatable<Wearable>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Wearable" /> class.
        /// </summary>
        /// <param name="fullAssetName">Internal name of asset with skin uuid  (required).</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="baseAssetName">Internal name of asset .</param>
        /// <param name="category">category.</param>
        /// <param name="tags">tags.</param>
        /// <param name="iconUrl">Cloudfront url of the icon. .</param>
        /// <param name="description">Description of asset .</param>
        /// <param name="wearableDefinition">JSON string representation of the wearable definition  (required).</param>
        /// <param name="createdBy">Cognito unique identifier for a user who made this wearable  (required).</param>
        /// <param name="thriftable">Status if the wearable is able to be thrifted or not.</param>
        public Wearable(string fullAssetName = default(string), string displayName = default(string), string baseAssetName = default(string), string category = default(string), List<string> tags = default(List<string>), string iconUrl = default(string), string description = default(string), string wearableDefinition = default(string), string createdBy = default(string), bool? thriftable = default(bool?))
        {
            // to ensure "fullAssetName" is required (not null)
            if (fullAssetName == null)
            {
                throw new InvalidDataException("fullAssetName is a required property for Wearable and cannot be null");
            }
            else
            {
                this.FullAssetName = fullAssetName;
            }
            // to ensure "wearableDefinition" is required (not null)
            if (wearableDefinition == null)
            {
                throw new InvalidDataException("wearableDefinition is a required property for Wearable and cannot be null");
            }
            else
            {
                this.WearableDefinition = wearableDefinition;
            }
            // to ensure "createdBy" is required (not null)
            if (createdBy == null)
            {
                throw new InvalidDataException("createdBy is a required property for Wearable and cannot be null");
            }
            else
            {
                this.CreatedBy = createdBy;
            }
            this.DisplayName = displayName;
            this.BaseAssetName = baseAssetName;
            this.Category = category;
            this.Tags = tags;
            this.IconUrl = iconUrl;
            this.Description = description;
            this.Thriftable = thriftable;
        }
        
        /// <summary>
        /// Wearable unique identifier for the skin
        /// </summary>
        /// <value>Wearable unique identifier for the skin</value>
        [DataMember(Name="wearableId", EmitDefaultValue=false)]
        public string WearableId { get; private set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public decimal? Created { get; private set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="lastModified", EmitDefaultValue=false)]
        public decimal? LastModified { get; private set; }

        /// <summary>
        /// Internal name of asset with skin uuid 
        /// </summary>
        /// <value>Internal name of asset with skin uuid </value>
        [DataMember(Name="fullAssetName", EmitDefaultValue=false)]
        public string FullAssetName { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Internal name of asset 
        /// </summary>
        /// <value>Internal name of asset </value>
        [DataMember(Name="baseAssetName", EmitDefaultValue=false)]
        public string BaseAssetName { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Cloudfront url of the icon. 
        /// </summary>
        /// <value>Cloudfront url of the icon. </value>
        [DataMember(Name="iconUrl", EmitDefaultValue=false)]
        public string IconUrl { get; set; }

        /// <summary>
        /// Description of asset 
        /// </summary>
        /// <value>Description of asset </value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// JSON string representation of the wearable definition 
        /// </summary>
        /// <value>JSON string representation of the wearable definition </value>
        [DataMember(Name="wearableDefinition", EmitDefaultValue=false)]
        public string WearableDefinition { get; set; }

        /// <summary>
        /// Cognito unique identifier for a user who made this wearable 
        /// </summary>
        /// <value>Cognito unique identifier for a user who made this wearable </value>
        [DataMember(Name="createdBy", EmitDefaultValue=false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Status if the wearable is able to be thrifted or not
        /// </summary>
        /// <value>Status if the wearable is able to be thrifted or not</value>
        [DataMember(Name="thriftable", EmitDefaultValue=false)]
        public bool? Thriftable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Wearable {\n");
            sb.Append("  WearableId: ").Append(WearableId).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  FullAssetName: ").Append(FullAssetName).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  BaseAssetName: ").Append(BaseAssetName).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  IconUrl: ").Append(IconUrl).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  WearableDefinition: ").Append(WearableDefinition).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  Thriftable: ").Append(Thriftable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Wearable);
        }

        /// <summary>
        /// Returns true if Wearable instances are equal
        /// </summary>
        /// <param name="input">Instance of Wearable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Wearable input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WearableId == input.WearableId ||
                    (this.WearableId != null &&
                    this.WearableId.Equals(input.WearableId))
                ) && 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.FullAssetName == input.FullAssetName ||
                    (this.FullAssetName != null &&
                    this.FullAssetName.Equals(input.FullAssetName))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.BaseAssetName == input.BaseAssetName ||
                    (this.BaseAssetName != null &&
                    this.BaseAssetName.Equals(input.BaseAssetName))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    input.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                ) && 
                (
                    this.IconUrl == input.IconUrl ||
                    (this.IconUrl != null &&
                    this.IconUrl.Equals(input.IconUrl))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.WearableDefinition == input.WearableDefinition ||
                    (this.WearableDefinition != null &&
                    this.WearableDefinition.Equals(input.WearableDefinition))
                ) && 
                (
                    this.CreatedBy == input.CreatedBy ||
                    (this.CreatedBy != null &&
                    this.CreatedBy.Equals(input.CreatedBy))
                ) && 
                (
                    this.Thriftable == input.Thriftable ||
                    (this.Thriftable != null &&
                    this.Thriftable.Equals(input.Thriftable))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WearableId != null)
                    hashCode = hashCode * 59 + this.WearableId.GetHashCode();
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                if (this.FullAssetName != null)
                    hashCode = hashCode * 59 + this.FullAssetName.GetHashCode();
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.BaseAssetName != null)
                    hashCode = hashCode * 59 + this.BaseAssetName.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.IconUrl != null)
                    hashCode = hashCode * 59 + this.IconUrl.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.WearableDefinition != null)
                    hashCode = hashCode * 59 + this.WearableDefinition.GetHashCode();
                if (this.CreatedBy != null)
                    hashCode = hashCode * 59 + this.CreatedBy.GetHashCode();
                if (this.Thriftable != null)
                    hashCode = hashCode * 59 + this.Thriftable.GetHashCode();
                return hashCode;
            }
        }
    }
}
