#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// AllOfCreateUploadSessionRequestUploadMode
    /// </summary>
    [DataContract]
        public partial class AllOfCreateUploadSessionRequestUploadMode :  IEquatable<AllOfCreateUploadSessionRequestUploadMode>
    {
        /// <summary>
        /// Gets or Sets the underlying UploadMode value
        /// </summary>
        [DataMember(Name="upload_mode", EmitDefaultValue=false)]
        public UploadMode Value { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AllOfCreateUploadSessionRequestUploadMode" /> class.
        /// </summary>
        public AllOfCreateUploadSessionRequestUploadMode(UploadMode value = default(UploadMode))
        {
            this.Value = value;
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AllOfCreateUploadSessionRequestUploadMode {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AllOfCreateUploadSessionRequestUploadMode);
        }

        /// <summary>
        /// Returns true if AllOfCreateUploadSessionRequestUploadMode instances are equal
        /// </summary>
        /// <param name="input">Instance of AllOfCreateUploadSessionRequestUploadMode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AllOfCreateUploadSessionRequestUploadMode input)
        {
            if (input == null)
                return false;

            return this.Value == input.Value;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }
    }
}
