#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// AttachFileResponse
    /// </summary>
    [DataContract]
        public partial class AttachFileResponse :  IEquatable<AttachFileResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachFileResponse" /> class.
        /// </summary>
        /// <param name="fileAttachments">fileAttachments (required).</param>
        /// <param name="knowledgeId">knowledgeId (required).</param>
        public AttachFileResponse(List<FileAttachmentRecord> fileAttachments = default(List<FileAttachmentRecord>), string knowledgeId = default(string))
        {
            // to ensure "fileAttachments" is required (not null)
            if (fileAttachments == null)
            {
                throw new InvalidDataException("fileAttachments is a required property for AttachFileResponse and cannot be null");
            }
            else
            {
                this.FileAttachments = fileAttachments;
            }
            // to ensure "knowledgeId" is required (not null)
            if (knowledgeId == null)
            {
                throw new InvalidDataException("knowledgeId is a required property for AttachFileResponse and cannot be null");
            }
            else
            {
                this.KnowledgeId = knowledgeId;
            }
        }
        
        /// <summary>
        /// Gets or Sets FileAttachments
        /// </summary>
        [DataMember(Name="file_attachments", EmitDefaultValue=false)]
        public List<FileAttachmentRecord> FileAttachments { get; set; }

        /// <summary>
        /// Gets or Sets KnowledgeId
        /// </summary>
        [DataMember(Name="knowledge_id", EmitDefaultValue=false)]
        public string KnowledgeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AttachFileResponse {\n");
            sb.Append("  FileAttachments: ").Append(FileAttachments).Append("\n");
            sb.Append("  KnowledgeId: ").Append(KnowledgeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AttachFileResponse);
        }

        /// <summary>
        /// Returns true if AttachFileResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AttachFileResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AttachFileResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FileAttachments == input.FileAttachments ||
                    this.FileAttachments != null &&
                    input.FileAttachments != null &&
                    this.FileAttachments.SequenceEqual(input.FileAttachments)
                ) && 
                (
                    this.KnowledgeId == input.KnowledgeId ||
                    (this.KnowledgeId != null &&
                    this.KnowledgeId.Equals(input.KnowledgeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FileAttachments != null)
                    hashCode = hashCode * 59 + this.FileAttachments.GetHashCode();
                if (this.KnowledgeId != null)
                    hashCode = hashCode * 59 + this.KnowledgeId.GetHashCode();
                return hashCode;
            }
        }
    }
}
