#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// A shareable stat for the daily card
    /// </summary>
    [DataContract]
        public partial class DailyStat :  IEquatable<DailyStat>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DailyStat" /> class.
        /// </summary>
        /// <param name="text">e.g., +12% more likely to manifest exactly what you need (required).</param>
        /// <param name="isPositive">True for positive stat, False for playful negative (required).</param>
        public DailyStat(string text = default(string), bool? isPositive = default(bool?))
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new InvalidDataException("text is a required property for DailyStat and cannot be null");
            }
            else
            {
                this.Text = text;
            }
            // to ensure "isPositive" is required (not null)
            if (isPositive == null)
            {
                throw new InvalidDataException("isPositive is a required property for DailyStat and cannot be null");
            }
            else
            {
                this.IsPositive = isPositive;
            }
        }
        
        /// <summary>
        /// e.g., +12% more likely to manifest exactly what you need
        /// </summary>
        /// <value>e.g., +12% more likely to manifest exactly what you need</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// True for positive stat, False for playful negative
        /// </summary>
        /// <value>True for positive stat, False for playful negative</value>
        [DataMember(Name="is_positive", EmitDefaultValue=false)]
        public bool? IsPositive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DailyStat {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  IsPositive: ").Append(IsPositive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DailyStat);
        }

        /// <summary>
        /// Returns true if DailyStat instances are equal
        /// </summary>
        /// <param name="input">Instance of DailyStat to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DailyStat input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.IsPositive == input.IsPositive ||
                    (this.IsPositive != null &&
                    this.IsPositive.Equals(input.IsPositive))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.IsPositive != null)
                    hashCode = hashCode * 59 + this.IsPositive.GetHashCode();
                return hashCode;
            }
        }
    }
}
