#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// Status values for Genie Brain session processing
    /// </summary>
    /// <value>Status values for Genie Brain session processing</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum GenieBrainSessionStatus
    {
        /// <summary>
        /// Enum CREATED for value: CREATED
        /// </summary>
        [EnumMember(Value = "CREATED")]
        CREATED = 1,
        /// <summary>
        /// Enum PROCESSING for value: PROCESSING
        /// </summary>
        [EnumMember(Value = "PROCESSING")]
        PROCESSING = 2,
        /// <summary>
        /// Enum WAITINGCOMPLETE for value: WAITING_COMPLETE
        /// </summary>
        [EnumMember(Value = "WAITING_COMPLETE")]
        WAITINGCOMPLETE = 3,
        /// <summary>
        /// Enum GENERATING for value: GENERATING
        /// </summary>
        [EnumMember(Value = "GENERATING")]
        GENERATING = 4,
        /// <summary>
        /// Enum RETRYING for value: RETRYING
        /// </summary>
        [EnumMember(Value = "RETRYING")]
        RETRYING = 5,
        /// <summary>
        /// Enum COMPLETED for value: COMPLETED
        /// </summary>
        [EnumMember(Value = "COMPLETED")]
        COMPLETED = 6,
        /// <summary>
        /// Enum FAILED for value: FAILED
        /// </summary>
        [EnumMember(Value = "FAILED")]
        FAILED = 7    }
}
