#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// Defines MessageSource
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum MessageSource
    {
        /// <summary>
        /// Enum UserTyped for value: user-typed
        /// </summary>
        [EnumMember(Value = "user-typed")]
        UserTyped = 1,
        /// <summary>
        /// Enum Preprompt for value: preprompt
        /// </summary>
        [EnumMember(Value = "preprompt")]
        Preprompt = 2,
        /// <summary>
        /// Enum FollowUp for value: follow-up
        /// </summary>
        [EnumMember(Value = "follow-up")]
        FollowUp = 3,
        /// <summary>
        /// Enum GreetingInstruction for value: greeting-instruction
        /// </summary>
        [EnumMember(Value = "greeting-instruction")]
        GreetingInstruction = 4,
        /// <summary>
        /// Enum WelcomeText for value: welcome-text
        /// </summary>
        [EnumMember(Value = "welcome-text")]
        WelcomeText = 5    }
}
