#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// PhotoPersonaFile
    /// </summary>
    [DataContract]
        public partial class PhotoPersonaFile :  IEquatable<PhotoPersonaFile>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhotoPersonaFile" /> class.
        /// </summary>
        /// <param name="bucket">bucket (required).</param>
        /// <param name="fileId">fileId.</param>
        /// <param name="objectKey">objectKey (required).</param>
        public PhotoPersonaFile(string bucket = default(string), string fileId = default(string), string objectKey = default(string))
        {
            // to ensure "bucket" is required (not null)
            if (bucket == null)
            {
                throw new InvalidDataException("bucket is a required property for PhotoPersonaFile and cannot be null");
            }
            else
            {
                this.Bucket = bucket;
            }
            // to ensure "objectKey" is required (not null)
            if (objectKey == null)
            {
                throw new InvalidDataException("objectKey is a required property for PhotoPersonaFile and cannot be null");
            }
            else
            {
                this.ObjectKey = objectKey;
            }
            this.FileId = fileId;
        }
        
        /// <summary>
        /// Gets or Sets Bucket
        /// </summary>
        [DataMember(Name="bucket", EmitDefaultValue=false)]
        public string Bucket { get; set; }

        /// <summary>
        /// Gets or Sets FileId
        /// </summary>
        [DataMember(Name="file_id", EmitDefaultValue=false)]
        public string FileId { get; set; }

        /// <summary>
        /// Gets or Sets ObjectKey
        /// </summary>
        [DataMember(Name="object_key", EmitDefaultValue=false)]
        public string ObjectKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhotoPersonaFile {\n");
            sb.Append("  Bucket: ").Append(Bucket).Append("\n");
            sb.Append("  FileId: ").Append(FileId).Append("\n");
            sb.Append("  ObjectKey: ").Append(ObjectKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhotoPersonaFile);
        }

        /// <summary>
        /// Returns true if PhotoPersonaFile instances are equal
        /// </summary>
        /// <param name="input">Instance of PhotoPersonaFile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhotoPersonaFile input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bucket == input.Bucket ||
                    (this.Bucket != null &&
                    this.Bucket.Equals(input.Bucket))
                ) && 
                (
                    this.FileId == input.FileId ||
                    (this.FileId != null &&
                    this.FileId.Equals(input.FileId))
                ) && 
                (
                    this.ObjectKey == input.ObjectKey ||
                    (this.ObjectKey != null &&
                    this.ObjectKey.Equals(input.ObjectKey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bucket != null)
                    hashCode = hashCode * 59 + this.Bucket.GetHashCode();
                if (this.FileId != null)
                    hashCode = hashCode * 59 + this.FileId.GetHashCode();
                if (this.ObjectKey != null)
                    hashCode = hashCode * 59 + this.ObjectKey.GetHashCode();
                return hashCode;
            }
        }
    }
}
