#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// PromptItem
    /// </summary>
    [DataContract]
        public partial class PromptItem :  IEquatable<PromptItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PromptItem" /> class.
        /// </summary>
        /// <param name="simplifiedText">simplifiedText (required).</param>
        /// <param name="text">text (required).</param>
        /// <param name="type">type (required).</param>
        public PromptItem(string simplifiedText = default(string), string text = default(string), string type = default(string))
        {
            // to ensure "simplifiedText" is required (not null)
            if (simplifiedText == null)
            {
                throw new InvalidDataException("simplifiedText is a required property for PromptItem and cannot be null");
            }
            else
            {
                this.SimplifiedText = simplifiedText;
            }
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new InvalidDataException("text is a required property for PromptItem and cannot be null");
            }
            else
            {
                this.Text = text;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for PromptItem and cannot be null");
            }
            else
            {
                this.Type = type;
            }
        }
        
        /// <summary>
        /// Gets or Sets SimplifiedText
        /// </summary>
        [DataMember(Name="simplified_text", EmitDefaultValue=false)]
        public string SimplifiedText { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PromptItem {\n");
            sb.Append("  SimplifiedText: ").Append(SimplifiedText).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PromptItem);
        }

        /// <summary>
        /// Returns true if PromptItem instances are equal
        /// </summary>
        /// <param name="input">Instance of PromptItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PromptItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SimplifiedText == input.SimplifiedText ||
                    (this.SimplifiedText != null &&
                    this.SimplifiedText.Equals(input.SimplifiedText))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SimplifiedText != null)
                    hashCode = hashCode * 59 + this.SimplifiedText.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }
    }
}
