#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// QueryScenarioConfigResponse
    /// </summary>
    [DataContract]
        public partial class QueryScenarioConfigResponse :  IEquatable<QueryScenarioConfigResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryScenarioConfigResponse" /> class.
        /// </summary>
        /// <param name="configs">configs (required).</param>
        /// <param name="nextCursor">nextCursor.</param>
        public QueryScenarioConfigResponse(List<ScenarioConfig> configs = default(List<ScenarioConfig>), string nextCursor = default(string))
        {
            // to ensure "configs" is required (not null)
            if (configs == null)
            {
                throw new InvalidDataException("configs is a required property for QueryScenarioConfigResponse and cannot be null");
            }
            else
            {
                this.Configs = configs;
            }
            this.NextCursor = nextCursor;
        }
        
        /// <summary>
        /// Gets or Sets Configs
        /// </summary>
        [DataMember(Name="configs", EmitDefaultValue=false)]
        public List<ScenarioConfig> Configs { get; set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [DataMember(Name="next_cursor", EmitDefaultValue=false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryScenarioConfigResponse {\n");
            sb.Append("  Configs: ").Append(Configs).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryScenarioConfigResponse);
        }

        /// <summary>
        /// Returns true if QueryScenarioConfigResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryScenarioConfigResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryScenarioConfigResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Configs == input.Configs ||
                    this.Configs != null &&
                    input.Configs != null &&
                    this.Configs.SequenceEqual(input.Configs)
                ) && 
                (
                    this.NextCursor == input.NextCursor ||
                    (this.NextCursor != null &&
                    this.NextCursor.Equals(input.NextCursor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Configs != null)
                    hashCode = hashCode * 59 + this.Configs.GetHashCode();
                if (this.NextCursor != null)
                    hashCode = hashCode * 59 + this.NextCursor.GetHashCode();
                return hashCode;
            }
        }
    }
}
