#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// UploadCompleteResponse
    /// </summary>
    [DataContract]
        public partial class UploadCompleteResponse :  IEquatable<UploadCompleteResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadCompleteResponse" /> class.
        /// </summary>
        /// <param name="sessionId">sessionId (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="totalUploadCount">totalUploadCount (required).</param>
        /// <param name="uploadStartedAt">uploadStartedAt (required).</param>
        /// <param name="uploadCompletedAt">uploadCompletedAt (required).</param>
        /// <param name="status">status (required).</param>
        public UploadCompleteResponse(string sessionId = default(string), string userId = default(string), int? totalUploadCount = default(int?), long? uploadStartedAt = default(long?), long? uploadCompletedAt = default(long?), string status = default(string))
        {
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new InvalidDataException("sessionId is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.SessionId = sessionId;
            }
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new InvalidDataException("userId is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.UserId = userId;
            }
            // to ensure "totalUploadCount" is required (not null)
            if (totalUploadCount == null)
            {
                throw new InvalidDataException("totalUploadCount is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.TotalUploadCount = totalUploadCount;
            }
            // to ensure "uploadStartedAt" is required (not null)
            if (uploadStartedAt == null)
            {
                throw new InvalidDataException("uploadStartedAt is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.UploadStartedAt = uploadStartedAt;
            }
            // to ensure "uploadCompletedAt" is required (not null)
            if (uploadCompletedAt == null)
            {
                throw new InvalidDataException("uploadCompletedAt is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.UploadCompletedAt = uploadCompletedAt;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for UploadCompleteResponse and cannot be null");
            }
            else
            {
                this.Status = status;
            }
        }
        
        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [DataMember(Name="session_id", EmitDefaultValue=false)]
        public string SessionId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="user_id", EmitDefaultValue=false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets TotalUploadCount
        /// </summary>
        [DataMember(Name="total_upload_count", EmitDefaultValue=false)]
        public int? TotalUploadCount { get; set; }

        /// <summary>
        /// Gets or Sets UploadStartedAt
        /// </summary>
        [DataMember(Name="upload_started_at", EmitDefaultValue=false)]
        public long? UploadStartedAt { get; set; }

        /// <summary>
        /// Gets or Sets UploadCompletedAt
        /// </summary>
        [DataMember(Name="upload_completed_at", EmitDefaultValue=false)]
        public long? UploadCompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UploadCompleteResponse {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  TotalUploadCount: ").Append(TotalUploadCount).Append("\n");
            sb.Append("  UploadStartedAt: ").Append(UploadStartedAt).Append("\n");
            sb.Append("  UploadCompletedAt: ").Append(UploadCompletedAt).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UploadCompleteResponse);
        }

        /// <summary>
        /// Returns true if UploadCompleteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of UploadCompleteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UploadCompleteResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SessionId == input.SessionId ||
                    (this.SessionId != null &&
                    this.SessionId.Equals(input.SessionId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.TotalUploadCount == input.TotalUploadCount ||
                    (this.TotalUploadCount != null &&
                    this.TotalUploadCount.Equals(input.TotalUploadCount))
                ) && 
                (
                    this.UploadStartedAt == input.UploadStartedAt ||
                    (this.UploadStartedAt != null &&
                    this.UploadStartedAt.Equals(input.UploadStartedAt))
                ) && 
                (
                    this.UploadCompletedAt == input.UploadCompletedAt ||
                    (this.UploadCompletedAt != null &&
                    this.UploadCompletedAt.Equals(input.UploadCompletedAt))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SessionId != null)
                    hashCode = hashCode * 59 + this.SessionId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.TotalUploadCount != null)
                    hashCode = hashCode * 59 + this.TotalUploadCount.GetHashCode();
                if (this.UploadStartedAt != null)
                    hashCode = hashCode * 59 + this.UploadStartedAt.GetHashCode();
                if (this.UploadCompletedAt != null)
                    hashCode = hashCode * 59 + this.UploadCompletedAt.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }
    }
}
