#pragma warning disable CS0472
/* 
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Genies.Persona.Client.SwaggerDateConverter;
namespace Genies.Persona.Model
{
    /// <summary>
    /// Response payload for voice configuration resources.
    /// </summary>
    [DataContract]
        public partial class VoiceConfigResponse :  IEquatable<VoiceConfigResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VoiceConfigResponse" /> class.
        /// </summary>
        /// <param name="voiceConfigId">voiceConfigId (required).</param>
        /// <param name="providerVoiceId">providerVoiceId.</param>
        /// <param name="provider">provider.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public VoiceConfigResponse(string voiceConfigId = default(string), string providerVoiceId = default(string), string provider = default(string), string name = default(string), string description = default(string), int? createdAt = default(int?), int? updatedAt = default(int?))
        {
            // to ensure "voiceConfigId" is required (not null)
            if (voiceConfigId == null)
            {
                throw new InvalidDataException("voiceConfigId is a required property for VoiceConfigResponse and cannot be null");
            }
            else
            {
                this.VoiceConfigId = voiceConfigId;
            }
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new InvalidDataException("createdAt is a required property for VoiceConfigResponse and cannot be null");
            }
            else
            {
                this.CreatedAt = createdAt;
            }
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new InvalidDataException("updatedAt is a required property for VoiceConfigResponse and cannot be null");
            }
            else
            {
                this.UpdatedAt = updatedAt;
            }
            this.ProviderVoiceId = providerVoiceId;
            this.Provider = provider;
            this.Name = name;
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets VoiceConfigId
        /// </summary>
        [DataMember(Name="voice_config_id", EmitDefaultValue=false)]
        public string VoiceConfigId { get; set; }

        /// <summary>
        /// Gets or Sets ProviderVoiceId
        /// </summary>
        [DataMember(Name="provider_voice_id", EmitDefaultValue=false)]
        public string ProviderVoiceId { get; set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [DataMember(Name="provider", EmitDefaultValue=false)]
        public string Provider { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public int? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name="updated_at", EmitDefaultValue=false)]
        public int? UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VoiceConfigResponse {\n");
            sb.Append("  VoiceConfigId: ").Append(VoiceConfigId).Append("\n");
            sb.Append("  ProviderVoiceId: ").Append(ProviderVoiceId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VoiceConfigResponse);
        }

        /// <summary>
        /// Returns true if VoiceConfigResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of VoiceConfigResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VoiceConfigResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VoiceConfigId == input.VoiceConfigId ||
                    (this.VoiceConfigId != null &&
                    this.VoiceConfigId.Equals(input.VoiceConfigId))
                ) && 
                (
                    this.ProviderVoiceId == input.ProviderVoiceId ||
                    (this.ProviderVoiceId != null &&
                    this.ProviderVoiceId.Equals(input.ProviderVoiceId))
                ) && 
                (
                    this.Provider == input.Provider ||
                    (this.Provider != null &&
                    this.Provider.Equals(input.Provider))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VoiceConfigId != null)
                    hashCode = hashCode * 59 + this.VoiceConfigId.GetHashCode();
                if (this.ProviderVoiceId != null)
                    hashCode = hashCode * 59 + this.ProviderVoiceId.GetHashCode();
                if (this.Provider != null)
                    hashCode = hashCode * 59 + this.Provider.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.UpdatedAt != null)
                    hashCode = hashCode * 59 + this.UpdatedAt.GetHashCode();
                return hashCode;
            }
        }
    }
}
