using System.Runtime.CompilerServices;

// Genies - same package
[assembly: InternalsVisibleTo("Genies.NafPlugin.Editor")]

// com.genies.sdk.avatareditor
[assembly: InternalsVisibleTo("Genies.Sdk.AvatarEditor")]
// com.genies.avatars.sdk
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk")]
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk.Editor")]
[assembly: InternalsVisibleTo("Genies.Avatars.Sdk.Sample")]
// com.genies.experience.core
[assembly: InternalsVisibleTo("DOTween.Modules.generated")]
[assembly: InternalsVisibleTo("DOTween.generated")]
[assembly: InternalsVisibleTo("Genies.Experience.Core")]
[assembly: InternalsVisibleTo("Genies.Experience.Core.generated")]
[assembly: InternalsVisibleTo("Genies.Experience.Shared.Bindings.generated")]
[assembly: InternalsVisibleTo("Genies.Naf.generated")]
[assembly: InternalsVisibleTo("Genies.Scripting.Bindings.generated")]
[assembly: InternalsVisibleTo("Genies.Sdk.Core.generated")]
[assembly: InternalsVisibleTo("LeanCommon.generated")]
[assembly: InternalsVisibleTo("LeanTouch.generated")]
[assembly: InternalsVisibleTo("UniTask.DOTween.generated")]
[assembly: InternalsVisibleTo("UniTask.generated")]
[assembly: InternalsVisibleTo("Unity.TextMeshPro.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AnimationModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.AudioModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.CoreModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.IMGUIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.InputLegacyModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.ParticleSystemModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.Physics2DModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.PhysicsModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.TerrainModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.TerrainPhysicsModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.UI.generated")]
[assembly: InternalsVisibleTo("UnityEngine.UIModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.VehiclesModule.generated")]
[assembly: InternalsVisibleTo("UnityEngine.WindModule.generated")]
[assembly: InternalsVisibleTo("mscorlib.generated")]
// com.genies.megaeditor
[assembly: InternalsVisibleTo("Genies.MegaEditor")]
[assembly: InternalsVisibleTo("SilverStudioAvatarDemo")]
[assembly: InternalsVisibleTo("SilverStudioBase")]
[assembly: InternalsVisibleTo("SilverStudioLookDemo")]
// com.genies.naf
[assembly: InternalsVisibleTo("Genies.Naf")]
[assembly: InternalsVisibleTo("Genies.Naf.Editor")]
// com.genies.naf.content
[assembly: InternalsVisibleTo("Genies.Naf.Addressables")]
[assembly: InternalsVisibleTo("Genies.Naf.Content")]
// com.genies.sdk.avatar
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Editor")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Samples.DebugSdkFunctions")]
[assembly: InternalsVisibleTo("Genies.Sdk.Avatar.Samples.StarterScenes")]
// com.genies.sdk.core
[assembly: InternalsVisibleTo("Genies.Sdk.Core")]
[assembly: InternalsVisibleTo("Genies.Sdk.Core.Editor")]
// com.genies.avatars.customization
[assembly: InternalsVisibleTo("Genies.Avatars.Customization")]
